import type { Locale } from "./i18n";

// Static UI string dictionary. DB content is localized separately via JSONB.
const bn = {
  // nav
  nav_home: "হোম",
  nav_doctors: "ডাক্তার খুঁজুন",
  nav_specialties: "বিশেষজ্ঞ বিভাগ",
  nav_hospitals: "হাসপাতাল",
  nav_areas: "থানা / উপজেলা",
  nav_blog: "ব্লগ",
  nav_contact: "যোগাযোগ",
  nav_about: "আমাদের সম্পর্কে",
  book_appointment: "অ্যাপয়েন্টমেন্ট নিন",
  call_for_help: "সাহায্যের জন্য কল করুন",
  doctor_add_profile: "ডাক্তার? প্রোফাইল যুক্ত করুন",
  menu: "মেনু",
  close: "বন্ধ করুন",
  call: "কল করুন",
  call_short: "কল",
  whatsapp: "হোয়াটসঅ্যাপ",

  // geo banner
  geo_viewing_from: "আপনি সম্ভবত",
  geo_viewing_suffix: "থেকে দেখছেন, আপনার এলাকার ডাক্তার আগে দেখানো হচ্ছে।",
  geo_change: "পরিবর্তন করুন",
  geo_pick_area: "থানা / উপজেলা বাছাই করুন",

  // hero / home
  hero_badge: "খুলনার #১ ডাক্তার ডিরেক্টরি",
  hero_title_1: "আপনার এলাকার বিশ্বস্ত ডাক্তার,",
  hero_title_2: "এক ক্লিকেই।",
  hero_sub: "খুলনার সেরা বিশেষজ্ঞ ডাক্তার খুঁজুন, সহজে অ্যাপয়েন্টমেন্ট নিন।",
  search_doctor_placeholder: "ডাক্তারের নাম লিখুন",
  search_by_name: "নাম দিয়ে খুঁজুন",
  select_area: "থানা / উপজেলা নির্বাচন করুন",
  select_district: "জেলা নির্বাচন করুন",
  search: "খুঁজুন",
  popular: "জনপ্রিয়:",
  verified_doctor: "যাচাইকৃত ডাক্তার",
  sec_specialties_eyebrow: "বিশেষজ্ঞ বিভাগ",
  sec_specialties_title: "রোগ অনুযায়ী সঠিক বিশেষজ্ঞ বেছে নিন",
  sec_area_eyebrow: "এলাকা অনুযায়ী",
  sec_area_title: "আপনার এলাকার কাছের ডাক্তার খুঁজুন",
  sec_area_sub: "খুলনার প্রতিটি এলাকার যাচাইকৃত ডাক্তার ও চেম্বারের তথ্য এক জায়গায়।",
  khulna_bd: "খুলনা, বাংলাদেশ",
  default_district_bn: "খুলনা",
  default_district_en: "Khulna",
  sec_featured_eyebrow: "ডাক্তার",
  sec_featured_title: "খুলনার জনপ্রিয় ও যাচাইকৃত ডাক্তার",
  view_all_doctors: "সব ডাক্তার দেখুন",
  no_doctors_yet: "ডাক্তার তালিকা শীঘ্রই যুক্ত হবে।",
  similar_doctors_title: "আপনার এলাকার আশেপাশে আরও ডাক্তার",
  similar_doctors_sub: "একই এলাকা বা কাছাকাছি এলাকার আরও যাচাইকৃত ডাক্তার",
  sec_how_eyebrow: "কীভাবে কাজ করে",
  sec_how_title: "মাত্র ৩টি সহজ ধাপ",
  step1_title: "ডাক্তার বা বিভাগ খুঁজুন",
  step1_text: "নাম, বিশেষজ্ঞ বিভাগ বা এলাকা দিয়ে সহজে খুঁজুন।",
  step2_title: "প্রোফাইল ও চেম্বার দেখুন",
  step2_text: "ডাক্তারের যোগ্যতা, চেম্বারের সময় ও ফি দেখে নিন।",
  step3_title: "কল করুন বা অ্যাপয়েন্টমেন্ট নিন",
  step3_text: "সরাসরি কল করুন অথবা অনলাইনে সময় বুক করুন।",
  sec_why_eyebrow: "কেন ডক্টরবন্ধু",
  sec_why_title: "আমরা যে কারণে আলাদা",
  why1_title: "যাচাইকৃত ডাক্তার",
  why1_text: "প্রতিটি ডাক্তারের তথ্য ও ডিগ্রি যাচাই করা হয়।",
  why2_title: "এলাকাভিত্তিক খোঁজ",
  why2_text: "আপনার এলাকার কাছের ডাক্তার সহজে খুঁজুন।",
  why3_title: "সহজ বুকিং",
  why3_text: "ঝামেলাহীন অনলাইন অ্যাপয়েন্টমেন্ট বুকিং।",
  why4_title: "২৪/৭ সহায়তা হেল্পলাইন",
  why4_text: "যেকোনো প্রয়োজনে আমাদের হেল্পলাইন পাশে আছে।",
  sec_hosp_eyebrow: "জনপ্রিয় হাসপাতাল ও ক্লিনিক",
  sec_hosp_title: "খুলনার পরিচিত হাসপাতাল",
  view_all: "সব দেখুন",
  details: "বিস্তারিত",
  cta_title: "আজই আপনার পছন্দের ডাক্তারের অ্যাপয়েন্টমেন্ট নিন",
  cta_sub: "যাচাইকৃত ডাক্তার, সঠিক চেম্বারের সময়সূচি আর সহজ বুকিং, সব এক জায়গায়।",
  sec_testi_eyebrow: "রোগীদের মতামত",
  sec_testi_title: "আমাদের সেবা নিয়ে যা বলেন",
  sec_blog_eyebrow: "স্বাস্থ্য টিপস ও ব্লগ",
  sec_blog_title: "সুস্থ থাকার সহজ পরামর্শ",
  view_all_articles: "সব আর্টিকেল",
  read_more: "পড়ুন",
  fordoc_badge: "ডাক্তারদের জন্য",
  fordoc_title: "আপনি কি একজন ডাক্তার? আপনার প্রোফাইল হাজারো রোগীর কাছে পৌঁছে দিন।",
  fordoc_sub: "প্রতিদিন খুলনার হাজারো রোগী ডক্টরবন্ধুতে ডাক্তার খোঁজেন। আপনার প্রোফাইল ভেরিফায়েড ও ফিচার্ড করে বেশি রোগীর কাছে পৌঁছান।",
  fordoc_cta: "প্রোফাইল যুক্ত করুন",
  fordoc_benefit1: "যাচাইকৃত ও ফিচার্ড প্রোফাইল ব্যাজ",
  fordoc_benefit2: "খুলনার হাজারো রোগীর কাছে পৌঁছান",
  fordoc_benefit3: "চেম্বার ও সময়সূচি নিজে আপডেট করুন",
  fordoc_benefit4: "অ্যাপয়েন্টমেন্ট ও কল সরাসরি আপনার কাছে",
  sec_faq_eyebrow: "সাধারণ জিজ্ঞাসা",
  sec_faq_title: "যা আপনি জানতে চান",
  helpline_title: "যেকোনো সাহায্যের জন্য কল করুন",
  helpline_sub: "আমাদের হেল্পলাইন সবসময় আপনার পাশে",

  // doctor card / listing
  featured_badge: "★ ফিচার্ড",
  verified_badge: "✓ ভেরিফায়েড",
  new_profile: "নতুন প্রোফাইল",
  fee: "ফি",
  taka: "টাকা",
  visit_fee: "ভিজিট ফি",
  listing_title: "খুলনার ডাক্তারদের তালিকা",
  listing_sub_prefix: "জন যাচাইকৃত ডাক্তার থেকে আপনার প্রয়োজন অনুযায়ী বেছে নিন।",
  listing_sub_empty: "আপনার প্রয়োজন অনুযায়ী ডাক্তার খুঁজুন।",
  filters: "ফিল্টার",
  clear_all: "সব মুছুন",
  filter_specialty: "বিভাগ",
  filter_area: "থানা / উপজেলা",
  filter_gender: "লিঙ্গ",
  male: "পুরুষ",
  female: "নারী",
  filter_fee: "ভিজিট ফি (টাকা)",
  max: "সর্বোচ্চ",
  apply_filters: "ফিল্টার প্রয়োগ করুন",
  search_placeholder: "ডাক্তার বা বিভাগের নাম",
  search_area_placeholder: "থানা বা জেলার নাম লিখে খুঁজুন...",
  no_search_results: "আপনার অনুসন্ধানের সাথে মিলে যায় এমন কোনো এলাকা পাওয়া যায়নি।",
  filter_by_specialty: "বিশেষজ্ঞ বিভাগ দিয়ে ফিল্টার করুন...",
  no_results: "কোনো তথ্য পাওয়া যায়নি",
  sort_relevance: "প্রাসঙ্গিকতা অনুযায়ী",
  sort_fee_asc: "ফি: কম থেকে বেশি",
  sort_fee_desc: "ফি: বেশি থেকে কম",
  sort_experience: "অভিজ্ঞতা অনুযায়ী",
  no_doctors_found: "কোনো ডাক্তার পাওয়া যায়নি",
  no_doctors_found_sub: "ফিল্টার পরিবর্তন করে আবার চেষ্টা করুন অথবা হেল্পলাইনে কল করুন:",

  // doctor detail
  breadcrumb_home: "হোম",
  breadcrumb_doctors: "ডাক্তার",
  about_doctor: "পরিচিতি",
  chambers_schedule: "চেম্বার ও সময়সূচি",
  chamber_info_soon: "চেম্বারের তথ্য শীঘ্রই যুক্ত হবে। বিস্তারিত জানতে হেল্পলাইনে কল করুন।",
  no_slots_for_day: "এই দিনের জন্য কোনো সময় নেই। অন্য একটি দিন বাছুন।",
  no_slots_available: "এই দিনের জন্য কোনো সময় নেই। অন্য একটি দিন বাছুন।",
  patient_reviews: "রোগীদের রিভিউ",
  no_reviews: "এখনো কোনো রিভিউ নেই।",
  faq_title: "সাধারণ জিজ্ঞাসা",
  experience: "অভিজ্ঞতা",
  years_plus: "+ বছর",
  patients_served_label: "রোগী দেখেছেন",
  call_to_know: "জানতে কল করুন",
  serial_note: "সিরিয়াল নিশ্চিত করতে অনুগ্রহ করে সময়মতো উপস্থিত থাকুন। জরুরি প্রয়োজনে হেল্পলাইনে কল করুন।",
  location_view: "লোকেশন দেখুন",
  specialist: "বিশেষজ্ঞ",

  // booking
  booking_title: "অ্যাপয়েন্টমেন্ট বুকিং",
  step_datetime: "তারিখ ও সময়",
  step_patient: "রোগীর তথ্য",
  step_confirm: "নিশ্চিত করুন",
  select_chamber: "চেম্বার নির্বাচন করুন",
  select_date: "তারিখ নির্বাচন করুন",
  select_time: "সময় নির্বাচন করুন",
  next_step: "পরবর্তী ধাপ",
  prev_step: "পূর্ববর্তী",
  patient_info_title: "রোগীর তথ্য দিন",
  patient_name: "রোগীর নাম",
  patient_name_placeholder: "পুরো নাম লিখুন",
  mobile_number: "মোবাইল নম্বর",
  age: "বয়স",
  age_placeholder: "বছর",
  problem_label: "সমস্যা বা লক্ষণ (সংক্ষেপে)",
  problem_placeholder: "যে সমস্যার জন্য দেখাতে চান",
  confirm_booking: "অ্যাপয়েন্টমেন্ট নিশ্চিত করুন",
  booking_pending: "বুক করা হচ্ছে...",
  booking_success_title: "অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে",
  booking_success_sub: "আপনার সিরিয়াল সফলভাবে বুক হয়েছে। আমরা ফোনে যোগাযোগ করে নিশ্চিত করব।",
  doctor_label: "ডাক্তার",
  datetime_label: "তারিখ ও সময়",
  serial_label: "সিরিয়াল নম্বর",
  back_home: "হোমে ফিরে যান",

  // specialty/area pages
  spec_page_title_prefix: "খুলনায় সেরা",
  spec_page_title_suffix: "ডাক্তার",
  spec_list_prefix: "খুলনার",
  spec_list_suffix: "ডাক্তারদের তালিকা",
  spec_by_area: "এলাকা অনুযায়ী",
  spec_faq_suffix: "নিয়ে সাধারণ জিজ্ঞাসা",
  area_page_suffix: "এলাকার ডাক্তার ও চেম্বার",
  search_by_specialty: "বিভাগ অনুযায়ী খুঁজুন",
  area_doctors_suffix: "র ডাক্তারগণ",
  combo_title_mid: "এলাকার",
  combo_doctor: "ডাক্তার",
  no_spec_doctors: "এই বিভাগে ডাক্তার শীঘ্রই যুক্ত হবে। সাহায্যের জন্য হেল্পলাইনে কল করুন:",
  no_area_doctors: "এই এলাকায় ডাক্তার শীঘ্রই যুক্ত হবে। সাহায্যের জন্য হেল্পলাইনে কল করুন:",
  no_combo_doctors_1: "এলাকায় এই মুহূর্তে",
  no_combo_doctors_2: "ডাক্তার তালিকাভুক্ত নেই।",
  see_all_spec_prefix: "খুলনার সব",
  see_all_spec_suffix: "ডাক্তার দেখুন →",
  other_areas_prefix: "অন্যান্য এলাকায়",
  other_specialties: "অন্যান্য বিভাগ",

  // hospitals
  hospitals_title: "আপনার সবচেয়ে কাছের হাসপাতাল ও ক্লিনিক",
  hospitals_sub: "আপনার সবচেয়ে কাছের পরিচিত হাসপাতাল ও ক্লিনিকের তালিকা। এলাকা অনুযায়ী হাসপাতাল, বিভাগ ও ডাক্তারের তথ্য এক জায়গায়।",
  departments_count_suffix: "টি বিভাগ",
  doctors_count_suffix: "+ ডাক্তার",
  view_details: "বিস্তারিত দেখুন",
  area_label: "এলাকা",
  departments: "বিভাগসমূহ",
  location: "লোকেশন",
  gallery: "গ্যালারি",
  hospital_doctors: "এই হাসপাতালের ডাক্তারগণ",
  doctors_info_soon: "ডাক্তারদের তথ্য শীঘ্রই যুক্ত হবে।",
  khulna: "খুলনা",
  filter_by_name: "নাম দিয়ে ফিল্টার করুন",
  filter_by_department: "বিভাগ দিয়ে ফিল্টার করুন",

  // blog
  blog_title: "স্বাস্থ্য টিপস ও ব্লগ",
  blog_sub: "সুস্থ থাকার সহজ পরামর্শ ও বিশেষজ্ঞদের লেখা পড়ুন।",
  all: "সব",
  no_articles: "আর্টিকেল শীঘ্রই প্রকাশিত হবে।",
  article_disclaimer: "মনে রাখবেন, এই লেখা শুধু সাধারণ তথ্যের জন্য। গুরুতর সমস্যায় অবশ্যই ডাক্তারের পরামর্শ নিন।",
  article_cta: "আপনার জন্য একজন ভালো ডাক্তার খুঁজছেন?",
  find_doctor: "ডাক্তার খুঁজুন",

  // for doctors
  fordoc_hero_title: "আপনার প্রোফাইল হাজারো রোগীর কাছে পৌঁছে দিন",
  fordoc_call_cta: "এ কল করুন",
  plans_title: "প্রমোশন প্ল্যান",
  plans_sub: "আপনার প্রয়োজন অনুযায়ী প্ল্যান বেছে নিন। যেকোনো প্ল্যানে যোগ দিতে যোগাযোগ করুন।",
  plan_popular: "জনপ্রিয়",
  plan_cta: "এই প্ল্যান নিন",
  fordoc_form_title: "প্রোফাইল যুক্ত করতে তথ্য দিন",
  fordoc_name_placeholder: "ডাক্তারের নাম",
  fordoc_specialty_placeholder: "বিশেষজ্ঞ বিভাগ",
  fordoc_message_placeholder: "চেম্বার ও প্ল্যান সম্পর্কে লিখুন",
  fordoc_submit: "তথ্য পাঠান",

  // contact
  contact_title: "যোগাযোগ করুন",
  contact_sub: "যেকোনো প্রয়োজনে আমরা আপনার পাশে আছি। নিচের যেকোনো মাধ্যমে যোগাযোগ করুন।",
  contact_patient_title: "রোগীদের জন্য সহায়তা",
  contact_patient_text: "ডাক্তার খুঁজতে, অ্যাপয়েন্টমেন্ট নিতে বা যেকোনো সাহায্যের জন্য আমাদের হেল্পলাইনে যোগাযোগ করুন।",
  contact_patient_cta: "হেল্পলাইনে কল করুন",
  contact_doctor_title: "ডাক্তারদের জন্য প্রোফাইল যুক্ত করা",
  contact_doctor_text: "আপনার প্রোফাইল ভেরিফায়েড ও ফিচার্ড করতে বা প্রমোশনের জন্য আমাদের সাথে কথা বলুন।",
  contact_doctor_cta: "প্রমোশনের জন্য যোগাযোগ",
  contact_form_title: "আমাদের মেসেজ পাঠান",
  your_name: "আপনার নাম",
  your_message: "আপনার বার্তা লিখুন",
  send: "পাঠিয়ে দিন",
  sending: "পাঠানো হচ্ছে...",
  direct_contact: "সরাসরি যোগাযোগ",
  whatsapp_message: "হোয়াটসঅ্যাপে মেসেজ দিন",
  our_address: "আমাদের ঠিকানা",

  // about
  about_suffix: "সম্পর্কে",
  about_intro_1: "খুলনার একটি বিশ্বস্ত ডাক্তার ডিরেক্টরি। আমাদের লক্ষ্য, প্রতিটি মানুষ যেন সহজে তার এলাকার সঠিক বিশেষজ্ঞ ডাক্তার খুঁজে পান এবং ঝামেলাহীনভাবে অ্যাপয়েন্টমেন্ট নিতে পারেন।",
  our_values: "আমাদের মূল্যবোধ",
  value1_title: "বিশ্বস্ততা",
  value1_text: "প্রতিটি ডাক্তারের তথ্য যাচাই করে তবেই তালিকাভুক্ত করা হয়।",
  value2_title: "সহজলভ্যতা",
  value2_text: "খুলনার যেকোনো এলাকা থেকে সহজে ডাক্তার খুঁজে নেওয়া যায়।",
  value3_title: "রোগীর যত্ন",
  value3_text: "রোগীর সময় ও সুবিধাকে সবচেয়ে বেশি গুরুত্ব দিই।",
  about_cta: "এখনই আপনার ডাক্তার খুঁজুন",

  // footer
  footer_tagline: "খুলনার বিশ্বস্ত ডাক্তার ডিরেক্টরি। এলাকা ও বিশেষজ্ঞ বিভাগ অনুযায়ী যাচাইকৃত ডাক্তার খুঁজুন ও সহজে অ্যাপয়েন্টমেন্ট নিন।",
  footer_popular_specs: "জনপ্রিয় বিভাগ",
  footer_by_area: "এলাকা অনুযায়ী",
  footer_area_doctors_suffix: "র ডাক্তার",
  footer_quick_links: "দ্রুত লিংক",
  footer_for_doctors: "ডাক্তারদের জন্য",
  footer_for_doctors_text: "ডাক্তার হিসেবে প্রোফাইল যুক্ত করতে বা প্রমোশনের জন্য যোগাযোগ করুন।",
  footer_contact_cta: "যোগাযোগ করুন",
  footer_rights: "সর্বস্বত্ব সংরক্ষিত।",
  terms: "শর্তাবলী",
  privacy: "প্রাইভেসি পলিসি",

  // misc
  doctors_unit: "জন ডাক্তার",
  posts_unit: "টি পোস্ট",
  not_found_title: "দুঃখিত, পেজটি খুঁজে পাওয়া যায়নি",
  not_found_sub: "আপনি যে পেজটি খুঁজছেন সেটি হয়তো সরিয়ে ফেলা হয়েছে বা এর ঠিকানা পরিবর্তন হয়েছে।",
  error_title: "কিছু একটা সমস্যা হয়েছে",
  error_sub: "সার্ভারে একটি ত্রুটি ঘটেছে। কিছুক্ষণ পরে আবার চেষ্টা করুন।",
  try_again: "আবার চেষ্টা করুন",
};

const en: typeof bn = {
  nav_home: "Home",
  nav_doctors: "Find Doctors",
  nav_specialties: "Specialties",
  nav_hospitals: "Hospitals",
  nav_areas: "By Thana / Upazila",
  nav_blog: "Blog",
  nav_contact: "Contact",
  nav_about: "About Us",
  book_appointment: "Book Appointment",
  call_for_help: "Call for help",
  doctor_add_profile: "Are you a doctor? List your profile",
  menu: "Menu",
  close: "Close",
  call: "Call Now",
  call_short: "Call",
  whatsapp: "WhatsApp",

  geo_viewing_from: "You seem to be browsing from",
  geo_viewing_suffix: ", showing doctors in your area first.",
  geo_change: "Change",
  geo_pick_area: "Pick your Thana / Upazila",

  hero_badge: "Khulna's #1 Doctor Directory",
  hero_title_1: "Trusted doctors in your area,",
  hero_title_2: "one click away.",
  hero_sub: "Find the best specialist doctors in Khulna and book appointments easily.",
  search_doctor_placeholder: "Enter doctor's name",
  search_by_name: "Search by name",
  select_area: "Select Thana / Upazila",
  select_district: "Select district",
  search: "Search",
  popular: "Popular:",
  verified_doctor: "Verified Doctor",
  sec_specialties_eyebrow: "Specialties",
  sec_specialties_title: "Choose the right specialist for your condition",
  sec_area_eyebrow: "By Area",
  sec_area_title: "Find doctors near your area",
  sec_area_sub: "Verified doctors and chamber details for every area of Khulna, in one place.",
  khulna_bd: "Khulna, Bangladesh",
  default_district_en: "Khulna",
  default_district_bn: "খুলনা",
  sec_featured_eyebrow: "Doctors",
  sec_featured_title: "Popular & verified doctors in Khulna",
  view_all_doctors: "View all doctors",
  no_doctors_yet: "Doctor listings coming soon.",
  similar_doctors_title: "More doctors near you",
  similar_doctors_sub: "More verified doctors from the same or nearby area",
  sec_how_eyebrow: "How It Works",
  sec_how_title: "Just 3 simple steps",
  step1_title: "Search by doctor or specialty",
  step1_text: "Search easily by name, specialty or area.",
  step2_title: "Review profile & chamber",
  step2_text: "Check the doctor's credentials, chamber hours and fee.",
  step3_title: "Call or book an appointment",
  step3_text: "Call directly or book a slot online.",
  sec_why_eyebrow: "Why DoctorBondhu",
  sec_why_title: "What makes us different",
  why1_title: "Verified Doctors",
  why1_text: "Every doctor's credentials are verified.",
  why2_title: "Area-based Search",
  why2_text: "Easily find doctors near your area.",
  why3_title: "Easy Booking",
  why3_text: "Hassle-free online appointment booking.",
  why4_title: "24/7 Helpline",
  why4_text: "Our helpline is always by your side.",
  sec_hosp_eyebrow: "Popular Hospitals & Clinics",
  sec_hosp_title: "Well-known hospitals in Khulna",
  view_all: "View all",
  details: "Details",
  cta_title: "Book your preferred doctor's appointment today",
  cta_sub: "Verified doctors, accurate chamber schedules and easy booking, all in one place.",
  sec_testi_eyebrow: "Patient Feedback",
  sec_testi_title: "What people say about our service",
  sec_blog_eyebrow: "Health Tips & Blog",
  sec_blog_title: "Simple advice for staying healthy",
  view_all_articles: "All articles",
  read_more: "Read",
  fordoc_badge: "For Doctors",
  fordoc_title: "Are you a doctor? Reach thousands of patients with your profile.",
  fordoc_sub: "Thousands of patients in Khulna search for doctors on DoctorBondhu every day. Get verified and featured to reach more of them.",
  fordoc_cta: "List Your Profile",
  fordoc_benefit1: "Verified & featured profile badges",
  fordoc_benefit2: "Reach thousands of patients in Khulna",
  fordoc_benefit3: "Update your chamber and schedule yourself",
  fordoc_benefit4: "Appointments and calls come directly to you",
  sec_faq_eyebrow: "FAQ",
  sec_faq_title: "What you want to know",
  helpline_title: "Call us for any assistance",
  helpline_sub: "Our helpline is always by your side",

  featured_badge: "★ Featured",
  verified_badge: "✓ Verified",
  new_profile: "New profile",
  fee: "Fee",
  taka: "BDT",
  visit_fee: "Visit Fee",
  listing_title: "Doctors in Khulna",
  listing_sub_prefix: "verified doctors to choose from, based on your needs.",
  listing_sub_empty: "Find doctors that match your needs.",
  filters: "Filters",
  clear_all: "Clear all",
  filter_specialty: "Specialty",
  filter_area: "Thana / Upazila",
  filter_gender: "Gender",
  male: "Male",
  female: "Female",
  filter_fee: "Visit fee (BDT)",
  max: "Max",
  apply_filters: "Apply Filters",
  search_placeholder: "Doctor or specialty name",
  search_area_placeholder: "Search by Thana or District name...",
  no_search_results: "No areas found matching your search.",
  filter_by_specialty: "Filter by specialty...",
  no_results: "No results",
  sort_relevance: "By relevance",
  sort_fee_asc: "Fee: low to high",
  sort_fee_desc: "Fee: high to low",
  sort_experience: "By experience",
  no_doctors_found: "No doctors found",
  no_doctors_found_sub: "Try changing the filters, or call our helpline:",

  breadcrumb_home: "Home",
  breadcrumb_doctors: "Doctors",
  about_doctor: "About",
  chambers_schedule: "Chambers & Schedule",
  chamber_info_soon: "Chamber details coming soon. Call the helpline to know more.",
  no_slots_for_day: "No slots on this day. Please pick another day.",
  no_slots_available: "No slots on this day. Please pick another day.",
  patient_reviews: "Patient Reviews",
  no_reviews: "No reviews yet.",
  faq_title: "FAQ",
  experience: "Experience",
  years_plus: "+ years",
  patients_served_label: "Patients served",
  call_to_know: "Call to know",
  serial_note: "Please arrive on time to confirm your serial. Call the helpline for urgent needs.",
  location_view: "View location",
  specialist: "Specialist",

  booking_title: "Book Appointment",
  step_datetime: "Date & Time",
  step_patient: "Patient Info",
  step_confirm: "Confirm",
  select_chamber: "Select chamber",
  select_date: "Select date",
  select_time: "Select time",
  next_step: "Next Step",
  prev_step: "Back",
  patient_info_title: "Enter patient details",
  patient_name: "Patient name",
  patient_name_placeholder: "Enter full name",
  mobile_number: "Mobile number",
  age: "Age",
  age_placeholder: "Years",
  problem_label: "Problem or symptoms (brief)",
  problem_placeholder: "What do you want to consult about",
  confirm_booking: "Confirm Appointment",
  booking_pending: "Booking...",
  booking_success_title: "Appointment Confirmed",
  booking_success_sub: "Your serial has been booked successfully. We'll confirm over the phone.",
  doctor_label: "Doctor",
  datetime_label: "Date & Time",
  serial_label: "Serial No.",
  back_home: "Back to Home",

  spec_page_title_prefix: "Best",
  spec_page_title_suffix: "Doctors in Khulna",
  spec_list_prefix: "List of",
  spec_list_suffix: "doctors in Khulna",
  spec_by_area: "by area",
  spec_faq_suffix: "FAQ",
  area_page_suffix: "Doctors & Chambers",
  search_by_specialty: "Browse by specialty",
  area_doctors_suffix: " doctors",
  combo_title_mid: "in",
  combo_doctor: "Doctors",
  no_spec_doctors: "Doctors in this specialty are coming soon. Call our helpline for help:",
  no_area_doctors: "Doctors in this area are coming soon. Call our helpline for help:",
  no_combo_doctors_1: "currently has no listed",
  no_combo_doctors_2: "doctors.",
  see_all_spec_prefix: "See all",
  see_all_spec_suffix: "doctors in Khulna →",
  other_areas_prefix: "In other areas:",
  other_specialties: "Other Specialties",

  hospitals_title: "Nearest Hospitals & Clinics",
  hospitals_sub: "Find well-known hospitals and clinics near you by area, with departments and doctor counts in one place.",
  departments_count_suffix: " departments",
  doctors_count_suffix: "+ doctors",
  view_details: "View details",
  area_label: "Area",
  departments: "Departments",
  location: "Location",
  gallery: "Gallery",
  hospital_doctors: "Doctors at this hospital",
  doctors_info_soon: "Doctor information coming soon.",
  khulna: "Khulna",
  filter_by_name: "Filter by name",
  filter_by_department: "Filter by department",

  blog_title: "Health Tips & Blog",
  blog_sub: "Read simple advice and expert articles on staying healthy.",
  all: "All",
  no_articles: "Articles coming soon.",
  article_disclaimer: "Remember, this article is for general information only. Always consult a doctor for serious conditions.",
  article_cta: "Looking for a good doctor?",
  find_doctor: "Find Doctors",

  fordoc_hero_title: "Reach thousands of patients with your profile",
  fordoc_call_cta: "Call",
  plans_title: "Promotion Plans",
  plans_sub: "Pick the plan that fits your needs. Contact us to join any plan.",
  plan_popular: "Popular",
  plan_cta: "Choose This Plan",
  fordoc_form_title: "Submit your details to get listed",
  fordoc_name_placeholder: "Doctor's name",
  fordoc_specialty_placeholder: "Specialty",
  fordoc_message_placeholder: "Tell us about your chamber and preferred plan",
  fordoc_submit: "Send Details",

  contact_title: "Contact Us",
  contact_sub: "We're here for you. Reach us through any of the channels below.",
  contact_patient_title: "Support for Patients",
  contact_patient_text: "Contact our helpline to find doctors, book appointments or for any assistance.",
  contact_patient_cta: "Call the helpline",
  contact_doctor_title: "Profile Listing for Doctors",
  contact_doctor_text: "Talk to us about getting verified, featured or promoted.",
  contact_doctor_cta: "Contact for promotion",
  contact_form_title: "Send us a message",
  your_name: "Your name",
  your_message: "Write your message",
  send: "Send",
  sending: "Sending...",
  direct_contact: "Direct Contact",
  whatsapp_message: "Message us on WhatsApp",
  our_address: "Our address",

  about_suffix: "About",
  about_intro_1: "is a trusted doctor directory for Khulna. Our goal is for everyone to easily find the right specialist in their area and book appointments without hassle.",
  our_values: "Our Values",
  value1_title: "Trust",
  value1_text: "Every doctor is verified before being listed.",
  value2_title: "Accessibility",
  value2_text: "Find doctors easily from any area of Khulna.",
  value3_title: "Patient Care",
  value3_text: "We value patients' time and convenience above all.",
  about_cta: "Find your doctor now",

  footer_tagline: "Khulna's trusted doctor directory. Find verified doctors by area and specialty, and book appointments easily.",
  footer_popular_specs: "Popular Specialties",
  footer_by_area: "By Area",
  footer_area_doctors_suffix: " doctors",
  footer_quick_links: "Quick Links",
  footer_for_doctors: "For Doctors",
  footer_for_doctors_text: "Contact us to list your profile or get promoted as a doctor.",
  footer_contact_cta: "Contact Us",
  footer_rights: "All rights reserved.",
  terms: "Terms of Service",
  privacy: "Privacy Policy",

  doctors_unit: "doctors",
  posts_unit: "posts",
  not_found_title: "Sorry, page not found",
  not_found_sub: "The page you're looking for may have been moved or its address has changed.",
  error_title: "Something went wrong",
  error_sub: "A server error occurred. Please try again shortly.",
  try_again: "Try Again",
};


export type Dict = typeof bn;

export function getDict(locale: Locale): Dict {
  return locale === "en" ? en : bn;
}
