import type { Locale } from "./i18n";

// Static UI string dictionary. DB content is localized separately via JSONB.
const bn = {
  // nav
  nav_home: "হোম",
  nav_doctors: "ডাক্তার খুঁজুন",
  nav_specialties: "বিশেষজ্ঞ বিভাগ",
  nav_hospitals: "হাসপাতাল",
  nav_districts: "জেলা",
  nav_areas: "শহর / গ্রাম",
  nav_blog: "ব্লগ",
  nav_contact: "যোগাযোগ",
  nav_about: "আমাদের সম্পর্কে",
  book_appointment: "অ্যাপয়েন্টমেন্ট নিন",
  call_for_help: "সাহায্যের জন্য কল করুন",
  doctor_add_profile: "ডাক্তার? প্রোফাইল যুক্ত করুন",
  menu: "মেনু",
  close: "বন্ধ করুন",
  call: "কল করুন",
  call_short: "কল",
  whatsapp: "হোয়াটসঅ্যাপ",

  // geo banner
  // {d} is replaced by the district name, rendered bold.
  geo_viewing_tpl: "আপনি সম্ভবত {d} থেকে দেখছেন, আপনার এলাকার ডাক্তার আগে দেখানো হচ্ছে।",
  geo_change: "পরিবর্তন করুন",
  geo_pick_area: "শহর / গ্রাম বাছাই করুন",
  // Shown instead of the "browsing from X" line when IP geo told us nothing —
  // we cannot claim a district we do not have, but we still need to offer the
  // picker, so the strip becomes a plain invitation.
  geo_unknown: "আপনার জেলা বেছে নিন, কাছের ডাক্তার আগে দেখানো হবে।",
  geo_choose_district: "জেলা বাছুন",
  // Shown when the visitor's chosen district has no doctors yet and the site
  // is quietly showing another district's instead. `{a}` = their district,
  // `{b}` = the district actually being shown.
  geo_no_doctors: "{a} জেলায় এখনো কোনো ডাক্তার যুক্ত হয়নি, তাই {b} সবচেয়ে কাছের ডাক্তার দেখানো হচ্ছে।",

  // hero / home
  hero_badge: "খুলনার #১ ডাক্তার ডিরেক্টরি",
  hero_title_1: "আপনার এলাকার বিশ্বস্ত ডাক্তার,",
  hero_title_2: "এক ক্লিকেই।",
  hero_sub: "খুলনার সেরা বিশেষজ্ঞ ডাক্তার খুঁজুন, সহজে অ্যাপয়েন্টমেন্ট নিন।",
  search_doctor_placeholder: "ডাক্তারের নাম লিখুন",
  search_by_name: "নাম দিয়ে খুঁজুন",
  select_area: "শহর / গ্রাম নির্বাচন করুন",
  select_district: "জেলা নির্বাচন করুন",
  search: "খুঁজুন",
  popular: "জনপ্রিয়:",
  verified_doctor: "যাচাইকৃত ডাক্তার",
  sec_specialties_eyebrow: "বিশেষজ্ঞ বিভাগ",
  sec_specialties_title: "রোগ অনুযায়ী সঠিক বিশেষজ্ঞ বেছে নিন",
  sec_area_eyebrow: "এলাকা অনুযায়ী",
  sec_area_title: "আপনার এলাকার কাছের ডাক্তার খুঁজুন",
  sec_area_sub: "খুলনার প্রতিটি এলাকার যাচাইকৃত ডাক্তার ও চেম্বারের তথ্য এক জায়গায়।",
  sec_district_title: "জেলা অনুযায়ী ডাক্তার খুঁজুন",
  sec_district_sub: "প্রতিটি জেলার যাচাইকৃত ডাক্তার ও চেম্বারের তালিকা। আপনার কাছের জেলা বেছে নিন।",
  khulna_bd: "খুলনা, বাংলাদেশ",
  default_district_bn: "খুলনা",
  default_district_en: "Khulna",
  sec_featured_eyebrow: "ডাক্তার",
  sec_featured_title: "খুলনার জনপ্রিয় ও যাচাইকৃত ডাক্তার",
  view_all_doctors: "সব ডাক্তার দেখুন",
  no_doctors_yet: "ডাক্তার তালিকা শীঘ্রই যুক্ত হবে।",
  similar_doctors_title: "আপনার এলাকার আশেপাশে আরও ডাক্তার",
  similar_doctors_sub: "একই এলাকা বা কাছাকাছি এলাকার আরও যাচাইকৃত ডাক্তার",
  sec_how_eyebrow: "কীভাবে কাজ করে",
  sec_how_title: "মাত্র ৩টি সহজ ধাপ",
  step1_title: "ডাক্তার বা বিভাগ খুঁজুন",
  step1_text: "নাম, বিশেষজ্ঞ বিভাগ বা এলাকা দিয়ে সহজে খুঁজুন।",
  step2_title: "প্রোফাইল ও চেম্বার দেখুন",
  step2_text: "ডাক্তারের যোগ্যতা, চেম্বারের সময় ও ফি দেখে নিন।",
  step3_title: "কল করুন বা অ্যাপয়েন্টমেন্ট নিন",
  step3_text: "সরাসরি কল করুন অথবা অনলাইনে সময় বুক করুন।",
  sec_why_eyebrow: "কেন ডক্টরস ফাইন্ড বাংলাদেশ",
  sec_why_title: "আমরা যে কারণে আলাদা",
  why1_title: "যাচাইকৃত ডাক্তার",
  why1_text: "প্রতিটি ডাক্তারের তথ্য ও ডিগ্রি যাচাই করা হয়।",
  why2_title: "এলাকাভিত্তিক খোঁজ",
  why2_text: "আপনার এলাকার কাছের ডাক্তার সহজে খুঁজুন।",
  why3_title: "সহজ বুকিং",
  why3_text: "ঝামেলাহীন অনলাইন অ্যাপয়েন্টমেন্ট বুকিং।",
  why4_title: "২৪/৭ সহায়তা হেল্পলাইন",
  why4_text: "যেকোনো প্রয়োজনে আমাদের হেল্পলাইন পাশে আছে।",
  sec_hosp_eyebrow: "জনপ্রিয় হাসপাতাল ও ক্লিনিক",
  sec_hosp_title: "খুলনার পরিচিত হাসপাতাল",
  view_all: "সব দেখুন",
  details: "বিস্তারিত",
  cta_title: "আজই আপনার পছন্দের ডাক্তারের অ্যাপয়েন্টমেন্ট নিন",
  cta_sub: "যাচাইকৃত ডাক্তার, সঠিক চেম্বারের সময়সূচি আর সহজ বুকিং, সব এক জায়গায়।",
  sec_testi_eyebrow: "রোগীদের মতামত",
  sec_testi_title: "আমাদের সেবা নিয়ে যা বলেন",
  sec_blog_eyebrow: "স্বাস্থ্য টিপস ও ব্লগ",
  sec_blog_title: "সুস্থ থাকার সহজ পরামর্শ",
  view_all_articles: "সব আর্টিকেল",
  read_more: "পড়ুন",
  fordoc_badge: "ডাক্তারদের জন্য",
  fordoc_title: "আপনি কি একজন ডাক্তার? আপনার প্রোফাইল হাজারো রোগীর কাছে পৌঁছে দিন।",
  fordoc_sub: "প্রতিদিন খুলনার হাজারো রোগী ডক্টরস ফাইন্ড বাংলাদেশতে ডাক্তার খোঁজেন। আপনার প্রোফাইল ভেরিফায়েড ও ফিচার্ড করে বেশি রোগীর কাছে পৌঁছান।",
  fordoc_cta: "প্রোফাইল যুক্ত করুন",
  fordoc_benefit1: "যাচাইকৃত ও ফিচার্ড প্রোফাইল ব্যাজ",
  fordoc_benefit2: "খুলনার হাজারো রোগীর কাছে পৌঁছান",
  fordoc_benefit3: "চেম্বার ও সময়সূচি নিজে আপডেট করুন",
  fordoc_benefit4: "অ্যাপয়েন্টমেন্ট ও কল সরাসরি আপনার কাছে",
  sec_faq_eyebrow: "সাধারণ জিজ্ঞাসা",
  sec_faq_title: "যা আপনি জানতে চান",
  helpline_title: "যেকোনো সাহায্যের জন্য কল করুন",
  helpline_sub: "আমাদের হেল্পলাইন সবসময় আপনার পাশে",

  // doctor card / listing
  featured_badge: "★ ফিচার্ড",
  verified_badge: "✓ ভেরিফায়েড",
  // BMDC badge and the explainer modal behind it. Deliberately worded as what
  // we checked and when, never as a judgement of the doctor's care.
  bmdc_badge: "✓ BMDC ভেরিফায়েড",
  bmdc_modal_title: "BMDC ভেরিফিকেশন",
  bmdc_modal_intro: "এই ডাক্তারের রেজিস্ট্রেশন বাংলাদেশ মেডিকেল অ্যান্ড ডেন্টাল কাউন্সিলের নিজস্ব রেজিস্টারে মিলিয়ে দেখা হয়েছে।",
  bmdc_reg_no_label: "রেজিস্ট্রেশন নম্বর",
  // The inline line under the doctor's name. Carries the "BMDC" prefix because,
  // unlike inside the modal, nothing around it has established the context.
  bmdc_reg_no_public: "BMDC রেজিস্ট্রেশন নম্বর",
  bmdc_reg_year_label: "রেজিস্ট্রেশনের বছর",
  bmdc_valid_till_label: "মেয়াদ",
  bmdc_how_title: "আমরা যেভাবে যাচাই করি",
  bmdc_how_1: "ডাক্তারের কাছ থেকে পাওয়া BMDC রেজিস্ট্রেশন নম্বরটি নেওয়া হয়।",
  bmdc_how_2: "নম্বরটি BMDC এর নিজস্ব ভেরিফিকেশন সাইটে খোঁজা হয়।",
  bmdc_how_3: "রেজিস্টারে থাকা নাম ও অবস্থা প্রোফাইলের তথ্যের সাথে মিলিয়ে দেখা হয়।",
  bmdc_how_4: "মিলে গেলে তবেই প্রোফাইলে BMDC ভেরিফায়েড ব্যাজ যুক্ত হয়।",
  bmdc_check_yourself: "নিজে যাচাই করুন",
  bmdc_official_site: "BMDC এর অফিশিয়াল ভেরিফিকেশন সাইট",
  bmdc_disclaimer: "এই ব্যাজের অর্থ শুধু এটুকু যে যাচাইয়ের দিন রেজিস্ট্রেশনটি বৈধ ছিল। এটি চিকিৎসার মান নিয়ে আমাদের কোনো মূল্যায়ন নয়। রেজিস্টারের তথ্য যেকোনো সময় বদলাতে পারে, তাই প্রয়োজনে উপরের লিংক থেকে নিজে দেখে নিন।",
  bmdc_expired_note: "এই রেজিস্ট্রেশনের মেয়াদ শেষ হয়ে গেছে। আমরা তথ্য হালনাগাদ করছি।",
  new_profile: "নতুন প্রোফাইল",
  fee: "ফি",
  taka: "টাকা",
  visit_fee: "ভিজিট ফি",
  listing_title: "খুলনার ডাক্তারদের তালিকা",
  listing_sub_prefix: "জন যাচাইকৃত ডাক্তার থেকে আপনার প্রয়োজন অনুযায়ী বেছে নিন।",
  listing_sub_empty: "আপনার প্রয়োজন অনুযায়ী ডাক্তার খুঁজুন।",
  filters: "ফিল্টার",
  clear_all: "সব মুছুন",
  filter_specialty: "বিভাগ",
  filter_area: "শহর / গ্রাম",
  filter_gender: "লিঙ্গ",
  male: "পুরুষ",
  female: "নারী",
  filter_fee: "ভিজিট ফি (টাকা)",
  max: "সর্বোচ্চ",
  apply_filters: "ফিল্টার প্রয়োগ করুন",
  search_placeholder: "ডাক্তার বা বিভাগের নাম",
  search_district_placeholder: "জেলার নাম লিখে খুঁজুন...",
  search_area_placeholder: "শহর, গ্রাম বা জেলার নাম লিখে খুঁজুন...",
  no_search_results: "আপনার অনুসন্ধানের সাথে মিলে যায় এমন কোনো এলাকা পাওয়া যায়নি।",
  // Search feedback. {n} is replaced with the localised number. Kept as four
  // separate phrases rather than one template because Bangla counts people
  // with "জন" and things with "টি", so a single string cannot serve both.
  clear_search: "সার্চ মুছুন",
  found_areas: "{n}টি এলাকা পাওয়া গেছে",
  found_districts: "{n}টি জেলা পাওয়া গেছে",
  found_specialties: "{n}টি বিভাগ পাওয়া গেছে",
  found_doctors: "{n} জন ডাক্তার পাওয়া গেছে",
  filter_by_specialty: "বিশেষজ্ঞ বিভাগ দিয়ে ফিল্টার করুন...",
  no_results: "কোনো তথ্য পাওয়া যায়নি",
  sort_relevance: "প্রাসঙ্গিকতা অনুযায়ী",
  sort_fee_asc: "ফি: কম থেকে বেশি",
  sort_fee_desc: "ফি: বেশি থেকে কম",
  sort_experience: "অভিজ্ঞতা অনুযায়ী",
  no_doctors_found: "কোনো ডাক্তার পাওয়া যায়নি",
  no_doctors_found_sub: "ফিল্টার পরিবর্তন করে আবার চেষ্টা করুন অথবা হেল্পলাইনে কল করুন:",

  // doctor detail
  breadcrumb_home: "হোম",
  breadcrumb_doctors: "ডাক্তার",
  about_doctor: "পরিচিতি",
  treated_conditions_title: "যে সকল রোগের চিকিৎসা করা হয়",
  chambers_schedule: "চেম্বার ও সময়সূচি",
  chamber_info_soon: "চেম্বারের তথ্য শীঘ্রই যুক্ত হবে। বিস্তারিত জানতে হেল্পলাইনে কল করুন।",
  no_slots_for_day: "এই দিনের জন্য কোনো সময় নেই। অন্য একটি দিন বাছুন।",
  no_slots_available: "এই দিনের জন্য কোনো সময় নেই। অন্য একটি দিন বাছুন।",
  patient_reviews: "রোগীদের রিভিউ",
  no_reviews: "এখনো কোনো রিভিউ নেই।",
  faq_title: "সাধারণ জিজ্ঞাসা",
  experience: "অভিজ্ঞতা",
  years_plus: "+ বছর",
  patients_served_label: "রোগী দেখেছেন",
  call_to_know: "জানতে কল করুন",
  serial_note: "সিরিয়াল নিশ্চিত করতে অনুগ্রহ করে সময়মতো উপস্থিত থাকুন। জরুরি প্রয়োজনে হেল্পলাইনে কল করুন।",
  location_view: "লোকেশন দেখুন",
  specialist: "বিশেষজ্ঞ",

  // booking
  booking_title: "অ্যাপয়েন্টমেন্ট বুকিং",
  step_datetime: "তারিখ ও সময়",
  step_patient: "রোগীর তথ্য",
  step_confirm: "নিশ্চিত করুন",
  select_chamber: "চেম্বার নির্বাচন করুন",
  select_date: "তারিখ নির্বাচন করুন",
  select_time: "সময় নির্বাচন করুন",
  next_step: "পরবর্তী ধাপ",
  prev_step: "পূর্ববর্তী",
  patient_info_title: "রোগীর তথ্য দিন",
  patient_name: "রোগীর নাম",
  patient_name_placeholder: "পুরো নাম লিখুন",
  mobile_number: "মোবাইল নম্বর",
  age: "বয়স",
  age_placeholder: "বছর",
  problem_label: "সমস্যা বা লক্ষণ (সংক্ষেপে)",
  problem_placeholder: "যে সমস্যার জন্য দেখাতে চান",
  confirm_booking: "অ্যাপয়েন্টমেন্ট নিশ্চিত করুন",
  booking_pending: "বুক করা হচ্ছে...",
  booking_success_title: "অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে",
  booking_success_sub: "আপনার সিরিয়াল সফলভাবে বুক হয়েছে। আমরা ফোনে যোগাযোগ করে নিশ্চিত করব।",
  doctor_label: "ডাক্তার",
  datetime_label: "তারিখ ও সময়",
  serial_label: "সিরিয়াল নম্বর",
  back_home: "হোমে ফিরে যান",

  // specialty/area pages
  spec_page_title_prefix: "খুলনায় সেরা",
  spec_page_title_suffix: "ডাক্তার",
  spec_list_prefix: "খুলনার",
  spec_list_suffix: "ডাক্তারদের তালিকা",
  spec_by_area: "এলাকা অনুযায়ী",
  spec_faq_suffix: "নিয়ে সাধারণ জিজ্ঞাসা",
  area_page_suffix: "এলাকার ডাক্তার ও চেম্বার",
  search_by_specialty: "বিভাগ অনুযায়ী খুঁজুন",
  area_doctors_suffix: "র ডাক্তারগণ",
  combo_title_mid: "এলাকার",
  combo_doctor: "ডাক্তার",
  no_spec_doctors: "এই বিভাগে ডাক্তার শীঘ্রই যুক্ত হবে। সাহায্যের জন্য হেল্পলাইনে কল করুন:",
  no_area_doctors: "এই এলাকায় ডাক্তার শীঘ্রই যুক্ত হবে। সাহায্যের জন্য হেল্পলাইনে কল করুন:",
  no_combo_doctors_1: "এলাকায় এই মুহূর্তে",
  no_combo_doctors_2: "ডাক্তার তালিকাভুক্ত নেই।",
  see_all_spec_prefix: "খুলনার সব",
  see_all_spec_suffix: "ডাক্তার দেখুন →",
  other_areas_prefix: "অন্যান্য এলাকায়",
  other_specialties: "অন্যান্য বিভাগ",

  // hospitals
  hospitals_title: "আপনার সবচেয়ে কাছের হাসপাতাল ও ক্লিনিক",
  hospitals_sub: "আপনার সবচেয়ে কাছের পরিচিত হাসপাতাল ও ক্লিনিকের তালিকা। এলাকা অনুযায়ী হাসপাতাল, বিভাগ ও ডাক্তারের তথ্য এক জায়গায়।",
  departments_count_suffix: "টি বিভাগ",
  doctors_count_suffix: "+ ডাক্তার",
  view_details: "বিস্তারিত দেখুন",
  area_label: "এলাকা",
  departments: "বিভাগসমূহ",
  location: "লোকেশন",
  gallery: "গ্যালারি",
  view_map: "ম্যাপ দেখুন",
  hospital_doctors: "এই হাসপাতালের ডাক্তারগণ",
  doctors_info_soon: "ডাক্তারদের তথ্য শীঘ্রই যুক্ত হবে।",
  khulna: "খুলনা",
  filter_by_name: "নাম দিয়ে ফিল্টার করুন",
  filter_by_department: "বিভাগ দিয়ে ফিল্টার করুন",

  // blog
  blog_title: "স্বাস্থ্য টিপস ও ব্লগ",
  blog_sub: "সুস্থ থাকার সহজ পরামর্শ ও বিশেষজ্ঞদের লেখা পড়ুন।",
  all: "সব",
  no_articles: "আর্টিকেল শীঘ্রই প্রকাশিত হবে।",
  article_disclaimer: "এই লেখাটি শুধুমাত্র সাধারণ স্বাস্থ্য সচেতনতার জন্য। এটি কোনো চিকিৎসা পরামর্শ, রোগ নির্ণয় বা চিকিৎসার বিকল্প নয়। উপসর্গ দেখা দিলে অবশ্যই রেজিস্টার্ড চিকিৎসকের পরামর্শ নিন। জরুরি অবস্থায় দেরি না করে ৯৯৯ নম্বরে কল করুন অথবা নিকটস্থ হাসপাতালে যান।",
  article_cta: "আপনার জন্য একজন ভালো ডাক্তার খুঁজছেন?",
  find_doctor: "ডাক্তার খুঁজুন",

  // for doctors
  fordoc_hero_title: "আপনার প্রোফাইল হাজারো রোগীর কাছে পৌঁছে দিন",
  fordoc_call_cta: "এ কল করুন",
  plans_title: "প্রমোশন প্ল্যান",
  plans_sub: "আপনার প্রয়োজন অনুযায়ী প্ল্যান বেছে নিন। যেকোনো প্ল্যানে যোগ দিতে যোগাযোগ করুন।",
  plan_popular: "জনপ্রিয়",
  plan_cta: "এই প্ল্যান নিন",

  // contact
  contact_title: "যোগাযোগ করুন",
  contact_sub: "যেকোনো প্রয়োজনে আমরা আপনার পাশে আছি। নিচের যেকোনো মাধ্যমে যোগাযোগ করুন।",
  contact_patient_title: "রোগীদের জন্য সহায়তা",
  contact_patient_text: "ডাক্তার খুঁজতে, অ্যাপয়েন্টমেন্ট নিতে বা যেকোনো সাহায্যের জন্য আমাদের হেল্পলাইনে যোগাযোগ করুন।",
  contact_patient_cta: "হেল্পলাইনে কল করুন",
  contact_doctor_title: "ডাক্তারদের জন্য প্রোফাইল যুক্ত করা",
  contact_doctor_text: "আপনার প্রোফাইল ভেরিফায়েড ও ফিচার্ড করতে বা প্রমোশনের জন্য আমাদের সাথে কথা বলুন।",
  contact_doctor_cta: "প্রমোশনের জন্য যোগাযোগ",
  contact_form_title: "আমাদের মেসেজ পাঠান",
  your_name: "আপনার নাম",
  your_email: "আপনার ইমেইল (ঐচ্ছিক)",
  your_message: "আপনার বার্তা লিখুন",
  send: "পাঠিয়ে দিন",
  sending: "পাঠানো হচ্ছে...",
  direct_contact: "সরাসরি যোগাযোগ",
  whatsapp_message: "হোয়াটসঅ্যাপে মেসেজ দিন",
  our_address: "আমাদের ঠিকানা",

  // ---- hub link blocks (crawlable internal links on the landing pages) ----
  // {d} district, {a} thana / upazila, {s} specialty.
  hub_areas_title_tpl: "{d} জেলার এলাকা অনুযায়ী ডাক্তার",
  hub_areas_desc: "আপনার সবচেয়ে কাছের থানা বা উপজেলা বেছে নিন। প্রতিটি এলাকার চেম্বার, সময়সূচি ও ভিজিট ফি আলাদা করে দেখানো আছে।",
  hub_specialties_title_tpl: "{d} জেলার বিশেষজ্ঞ বিভাগ",
  hub_specialties_desc: "কোন সমস্যায় কোন বিশেষজ্ঞ দেখাবেন জানা থাকলে সরাসরি সেই বিভাগে যান।",
  hub_hospitals_title_tpl: "{d} জেলার হাসপাতাল ও ক্লিনিক",
  hub_hospitals_desc: "হাসপাতাল অনুযায়ী ডাক্তার, বিভাগ ও যোগাযোগের তথ্য দেখুন।",
  hub_area_specialties_title_tpl: "{a} এলাকায় বিভাগ অনুযায়ী ডাক্তার",
  hub_area_specialties_desc: "এই এলাকায় যে বিশেষজ্ঞ বিভাগগুলোর ডাক্তার আছেন। সরাসরি আপনার প্রয়োজনের বিভাগে যান।",
  hub_specialty_districts_title_tpl: "জেলা অনুযায়ী {s}",
  hub_specialty_districts_desc: "যে জেলাগুলোতে এই বিভাগের ডাক্তার আছেন। আপনার জেলা বেছে নিলে শুধু সেখানকার তালিকা দেখবেন।",
  hub_specialty_areas_title_tpl: "এলাকা অনুযায়ী {s} ডাক্তার",
  hub_specialty_areas_desc: "যে এলাকাগুলোতে এই বিভাগের ডাক্তার আছেন। আপনার কাছের এলাকা বেছে নিন।",
  // Shown on a listing card whose entity has no doctors yet. The card used to
  // render nothing at all in that slot, which reads as a listing that failed to
  // load rather than a place we do not cover yet.
  coming_soon: "শীঘ্রই আসছে",
  hub_popular_searches_title: "জনপ্রিয় খোঁজ",
  hub_popular_searches_desc: "যে বিভাগ ও এলাকার সমন্বয়গুলো সবচেয়ে বেশি খোঁজা হয়। এক ক্লিকেই সেই তালিকায় যান।",
  hub_recent_doctors_title: "সদ্য হালনাগাদ হওয়া ডাক্তার",
  hub_recent_doctors_desc: "যেসব প্রোফাইলের তথ্য, চেম্বার বা সময়সূচি সবচেয়ে সম্প্রতি যাচাই ও হালনাগাদ করা হয়েছে।",
  hub_districts_title: "জেলা অনুযায়ী ডাক্তার",
  hub_districts_desc: "সারা বাংলাদেশের যে জেলাগুলোতে আমাদের যাচাইকৃত ডাক্তার আছেন। আপনার জেলা বেছে নিন।",
  view_all_districts: "সব জেলা দেখুন",
  hub_nearby_areas_title_tpl: "{d} জেলার আশপাশের এলাকা",
  hub_nearby_areas_desc: "একই জেলার অন্য থানা ও উপজেলার ডাক্তার দেখুন।",
  hub_related_title: "সম্পর্কিত পেজ",
  hub_all_area_doctors_tpl: "{a} এলাকার সব ডাক্তার",
  hub_all_district_doctors_tpl: "{d} জেলার সব ডাক্তার",
  view_all_areas: "সব এলাকা দেখুন",
  view_all_specialties: "সব বিভাগ দেখুন",
  view_all_hospitals: "সব হাসপাতাল দেখুন",
  // Fallback body copy for a district that has no admin-written intro yet.
  // {d} is the district name with the Bangla possessive already applied.
  // Pipe-separated so one dictionary entry can produce the `knowsAbout` array
  // in the Organization JSON-LD. See ldOrganization in seo-utils.ts.
  org_knows_about: "বিশেষজ্ঞ ডাক্তার ডিরেক্টরি|ডাক্তারের চেম্বার ও সময়সূচি|হাসপাতাল ও ক্লিনিক|ডাক্তার অ্যাপয়েন্টমেন্ট|বাংলাদেশের স্বাস্থ্যসেবা তথ্য",
  district_intro_fallback_tpl: "{d} যাচাইকৃত ডাক্তারদের সম্পূর্ণ তালিকা এক জায়গায়। প্রতিটি প্রোফাইলে ডিগ্রি, অভিজ্ঞতা, চেম্বারের ঠিকানা, বসার সময় ও ভিজিট ফি দেওয়া আছে, তাই যাওয়ার আগেই আপনি জানতে পারবেন কোথায় কখন যেতে হবে। বিভাগ, এলাকা বা হাসপাতাল অনুযায়ী ফিল্টার করে আপনার কাছের ডাক্তার বেছে নিন এবং সরাসরি অ্যাপয়েন্টমেন্ট নিন।",
  district_faq_title: "সাধারণ জিজ্ঞাসা",

  // about
  about_suffix: "সম্পর্কে",
  about_intro_1: "বাংলাদেশের একটি বিশ্বস্ত ডাক্তার ডিরেক্টরি। আমাদের লক্ষ্য, প্রতিটি মানুষ যেন সহজে তার এলাকার সঠিক বিশেষজ্ঞ ডাক্তার খুঁজে পান এবং ঝামেলাহীনভাবে অ্যাপয়েন্টমেন্ট নিতে পারেন।",
  our_values: "আমাদের মূল্যবোধ",
  value1_title: "বিশ্বস্ততা",
  value1_text: "প্রতিটি ডাক্তারের তথ্য যাচাই করে তবেই তালিকাভুক্ত করা হয়।",
  value2_title: "সহজলভ্যতা",
  value2_text: "খুলনার যেকোনো এলাকা থেকে সহজে ডাক্তার খুঁজে নেওয়া যায়।",
  value3_title: "রোগীর যত্ন",
  value3_text: "রোগীর সময় ও সুবিধাকে সবচেয়ে বেশি গুরুত্ব দিই।",
  about_cta: "এখনই আপনার ডাক্তার খুঁজুন",

  // ---- about: how the directory works, verification, editorial policy ----
  // Health information is a YMYL topic, so the site has to state plainly who
  // publishes it, where the data comes from, and how it is checked.
  about_how_title: "আমরা কীভাবে কাজ করি",
  about_how_text: "আমরা কোনো হাসপাতাল বা চেম্বার পরিচালনা করি না এবং কোনো চিকিৎসা সেবা দিই না। আমরা একটি ডিরেক্টরি, অর্থাৎ ডাক্তারদের প্রকাশ্য তথ্য এক জায়গায় গুছিয়ে রাখি যাতে আপনি সহজে খুঁজে পান ও যোগাযোগ করতে পারেন। অ্যাপয়েন্টমেন্টের অনুরোধ আমরা সংশ্লিষ্ট চেম্বারে পৌঁছে দিই।",
  about_verify_title: "তথ্য যাচাইয়ের পদ্ধতি",
  about_verify_intro: "প্রতিটি প্রোফাইল প্রকাশের আগে আমরা এই ধাপগুলো অনুসরণ করি:",
  about_verify_1: "তথ্য সংগ্রহ করা হয় সরাসরি ডাক্তার বা তার চেম্বার থেকে, অথবা হাসপাতালের প্রকাশ্য তালিকা থেকে।",
  about_verify_2: "নাম, ডিগ্রি ও বিশেষজ্ঞ বিভাগ চেম্বার বা হাসপাতালের দেওয়া তথ্যের সাথে মিলিয়ে দেখা হয়।",
  about_verify_3: "চেম্বারের ঠিকানা, বসার সময় ও ভিজিট ফি প্রকাশের আগে ফোনে নিশ্চিত করা হয়।",
  about_verify_4: "যাচাই সম্পন্ন হলে প্রোফাইলে যাচাইকৃত ব্যাজ যুক্ত হয়। যাচাই না হওয়া প্রোফাইলে এই ব্যাজ থাকে না।",
  about_verified_badge_note: "যাচাইকৃত ব্যাজের অর্থ আমরা তথ্যগুলো মিলিয়ে দেখেছি। এটি কোনো ডাক্তারের চিকিৎসার মান নিয়ে আমাদের মূল্যায়ন নয়।",
  about_editorial_title: "তথ্য হালনাগাদ ও সম্পাদনা নীতি",
  about_editorial_text: "চেম্বারের সময় ও ফি বদলাতে পারে, তাই আমরা নিয়মিত তথ্য হালনাগাদ করি এবং কোনো ভুল জানানো হলে যাচাই করে দ্রুত সংশোধন করি। ব্লগের লেখাগুলো সাধারণ স্বাস্থ্য তথ্য, এগুলো কোনো নির্দিষ্ট রোগ নির্ণয় বা চিকিৎসার পরামর্শ নয়।",
  about_disclaimer_title: "চিকিৎসা সংক্রান্ত দাবিত্যাগ",
  about_disclaimer_text: "এই সাইটের কোনো তথ্য ডাক্তারের পরামর্শের বিকল্প নয়। শারীরিক সমস্যায় সবসময় একজন যোগ্য চিকিৎসকের সরাসরি পরামর্শ নিন। জরুরি অবস্থায় দেরি না করে নিকটস্থ হাসপাতালে যান বা জাতীয় জরুরি সেবা ৯৯৯ নম্বরে কল করুন।",
  about_publisher_title: "প্রকাশক ও যোগাযোগ",
  about_publisher_text: "এই সাইটটি পরিচালনা করে:",
  about_correction_title: "ভুল তথ্য জানান",
  about_correction_text: "কোনো ডাক্তারের তথ্য ভুল বা পুরনো মনে হলে আমাদের জানান। আমরা যাচাই করে সংশোধন করব অথবা প্রোফাইলটি সরিয়ে নেব।",
  about_correction_cta: "সংশোধনের জন্য জানান",

  // footer
  footer_tagline: "খুলনার বিশ্বস্ত ডাক্তার ডিরেক্টরি। এলাকা ও বিশেষজ্ঞ বিভাগ অনুযায়ী যাচাইকৃত ডাক্তার খুঁজুন ও সহজে অ্যাপয়েন্টমেন্ট নিন।",
  footer_popular_specs: "জনপ্রিয় বিভাগ",
  footer_by_area: "এলাকা অনুযায়ী",
  footer_area_doctors_suffix: " ডাক্তার",
  footer_quick_links: "দ্রুত লিংক",
  footer_for_doctors: "ডাক্তারদের জন্য",
  footer_for_doctors_text: "ডাক্তার হিসেবে প্রোফাইল যুক্ত করতে বা প্রমোশনের জন্য যোগাযোগ করুন।",
  footer_contact_cta: "যোগাযোগ করুন",
  footer_rights: "সর্বস্বত্ব সংরক্ষিত।",
  terms: "শর্তাবলী",
  privacy: "প্রাইভেসি পলিসি",

  // misc
  doctors_unit: "জন ডাক্তার",
  posts_unit: "টি পোস্ট",
  not_found_title: "দুঃখিত, পেজটি খুঁজে পাওয়া যায়নি",
  not_found_sub: "আপনি যে পেজটি খুঁজছেন সেটি হয়তো সরিয়ে ফেলা হয়েছে বা এর ঠিকানা পরিবর্তন হয়েছে।",
  error_title: "কিছু একটা সমস্যা হয়েছে",
  error_sub: "সার্ভারে একটি ত্রুটি ঘটেছে। কিছুক্ষণ পরে আবার চেষ্টা করুন।",
  try_again: "আবার চেষ্টা করুন",
};

const en: typeof bn = {
  nav_home: "Home",
  nav_doctors: "Find Doctors",
  nav_specialties: "Specialties",
  nav_hospitals: "Hospitals",
  nav_districts: "District",
  nav_areas: "Town / Village",
  nav_blog: "Blog",
  nav_contact: "Contact",
  nav_about: "About Us",
  book_appointment: "Book Appointment",
  call_for_help: "Call for help",
  doctor_add_profile: "Are you a doctor? List your profile",
  menu: "Menu",
  close: "Close",
  call: "Call Now",
  call_short: "Call",
  whatsapp: "WhatsApp",

  geo_viewing_tpl: "You seem to be browsing from {d}, showing doctors in your area first.",
  geo_change: "Change",
  geo_pick_area: "Pick your Town / Village",
  geo_unknown: "Choose your district to see the nearest doctors first.",
  geo_choose_district: "Choose district",
  geo_no_doctors: "No doctors have been added in {a} yet, so we're showing the nearest ones from {b}.",

  hero_badge: "Khulna's #1 Doctor Directory",
  hero_title_1: "Trusted doctors in your area,",
  hero_title_2: "one click away.",
  hero_sub: "Find the best specialist doctors in Khulna and book appointments easily.",
  search_doctor_placeholder: "Enter doctor's name",
  search_by_name: "Search by name",
  select_area: "Select Town / Village",
  select_district: "Select district",
  search: "Search",
  popular: "Popular:",
  verified_doctor: "Verified Doctor",
  sec_specialties_eyebrow: "Specialties",
  sec_specialties_title: "Choose the right specialist for your condition",
  sec_area_eyebrow: "By Area",
  sec_area_title: "Find doctors near your area",
  sec_area_sub: "Verified doctors and chamber details for every area of Khulna, in one place.",
  sec_district_title: "Find Doctors by District",
  sec_district_sub: "Find verified doctors and chambers for every district. Pick the one nearest to you.",
  khulna_bd: "Khulna, Bangladesh",
  default_district_en: "Khulna",
  default_district_bn: "খুলনা",
  sec_featured_eyebrow: "Doctors",
  sec_featured_title: "Popular & verified doctors in Khulna",
  view_all_doctors: "View all doctors",
  no_doctors_yet: "Doctor listings coming soon.",
  similar_doctors_title: "More doctors near you",
  similar_doctors_sub: "More verified doctors from the same or nearby area",
  sec_how_eyebrow: "How It Works",
  sec_how_title: "Just 3 simple steps",
  step1_title: "Search by doctor or specialty",
  step1_text: "Search easily by name, specialty or area.",
  step2_title: "Review profile & chamber",
  step2_text: "Check the doctor's credentials, chamber hours and fee.",
  step3_title: "Call or book an appointment",
  step3_text: "Call directly or book a slot online.",
  sec_why_eyebrow: "Why Doctors Find Bangladesh",
  sec_why_title: "What makes us different",
  why1_title: "Verified Doctors",
  why1_text: "Every doctor's credentials are verified.",
  why2_title: "Area-based Search",
  why2_text: "Easily find doctors near your area.",
  why3_title: "Easy Booking",
  why3_text: "Hassle-free online appointment booking.",
  why4_title: "24/7 Helpline",
  why4_text: "Our helpline is always by your side.",
  sec_hosp_eyebrow: "Popular Hospitals & Clinics",
  sec_hosp_title: "Well-known hospitals in Khulna",
  view_all: "View all",
  details: "Details",
  cta_title: "Book your preferred doctor's appointment today",
  cta_sub: "Verified doctors, accurate chamber schedules and easy booking, all in one place.",
  sec_testi_eyebrow: "Patient Feedback",
  sec_testi_title: "What people say about our service",
  sec_blog_eyebrow: "Health Tips & Blog",
  sec_blog_title: "Simple advice for staying healthy",
  view_all_articles: "All articles",
  read_more: "Read",
  fordoc_badge: "For Doctors",
  fordoc_title: "Are you a doctor? Reach thousands of patients with your profile.",
  fordoc_sub: "Thousands of patients in Khulna search for doctors on Doctors Find Bangladesh every day. Get verified and featured to reach more of them.",
  fordoc_cta: "List Your Profile",
  fordoc_benefit1: "Verified & featured profile badges",
  fordoc_benefit2: "Reach thousands of patients in Khulna",
  fordoc_benefit3: "Update your chamber and schedule yourself",
  fordoc_benefit4: "Appointments and calls come directly to you",
  sec_faq_eyebrow: "FAQ",
  sec_faq_title: "What you want to know",
  helpline_title: "Call us for any assistance",
  helpline_sub: "Our helpline is always by your side",

  featured_badge: "★ Featured",
  verified_badge: "✓ Verified",
  bmdc_badge: "✓ BMDC Verified",
  bmdc_modal_title: "BMDC Verification",
  bmdc_modal_intro: "This doctor's registration was checked against the Bangladesh Medical & Dental Council's own register.",
  bmdc_reg_no_label: "Registration number",
  bmdc_reg_no_public: "BMDC registration number",
  bmdc_reg_year_label: "Registered since",
  bmdc_valid_till_label: "Valid till",
  bmdc_how_title: "How we verify",
  bmdc_how_1: "We collect the BMDC registration number from the doctor.",
  bmdc_how_2: "We look that number up on BMDC's own verification site.",
  bmdc_how_3: "We match the name and status on the register against the profile.",
  bmdc_how_4: "Only when they match does the profile get the BMDC Verified badge.",
  bmdc_check_yourself: "Check it yourself",
  bmdc_official_site: "BMDC official verification site",
  bmdc_disclaimer: "This badge means only that the registration was valid on the day we checked it. It is not our assessment of the doctor's care. Register entries can change at any time, so please use the link above if you need to confirm.",
  bmdc_expired_note: "This registration has expired. We are updating our records.",
  new_profile: "New profile",
  fee: "Fee",
  taka: "BDT",
  visit_fee: "Visit Fee",
  listing_title: "Doctors in Khulna",
  listing_sub_prefix: "verified doctors to choose from, based on your needs.",
  listing_sub_empty: "Find doctors that match your needs.",
  filters: "Filters",
  clear_all: "Clear all",
  filter_specialty: "Specialty",
  filter_area: "Town / Village",
  filter_gender: "Gender",
  male: "Male",
  female: "Female",
  filter_fee: "Visit fee (BDT)",
  max: "Max",
  apply_filters: "Apply Filters",
  search_placeholder: "Doctor or specialty name",
  search_district_placeholder: "Search by District name...",
  search_area_placeholder: "Search by Town, Village or District name...",
  no_search_results: "No areas found matching your search.",
  clear_search: "Clear search",
  found_areas: "{n} areas found",
  found_districts: "{n} districts found",
  found_specialties: "{n} specialties found",
  found_doctors: "{n} doctors found",
  filter_by_specialty: "Filter by specialty...",
  no_results: "No results",
  sort_relevance: "By relevance",
  sort_fee_asc: "Fee: low to high",
  sort_fee_desc: "Fee: high to low",
  sort_experience: "By experience",
  no_doctors_found: "No doctors found",
  no_doctors_found_sub: "Try changing the filters, or call our helpline:",

  breadcrumb_home: "Home",
  breadcrumb_doctors: "Doctors",
  about_doctor: "About",
  treated_conditions_title: "Conditions treated",
  chambers_schedule: "Chambers & Schedule",
  chamber_info_soon: "Chamber details coming soon. Call the helpline to know more.",
  no_slots_for_day: "No slots on this day. Please pick another day.",
  no_slots_available: "No slots on this day. Please pick another day.",
  patient_reviews: "Patient Reviews",
  no_reviews: "No reviews yet.",
  faq_title: "FAQ",
  experience: "Experience",
  years_plus: "+ years",
  patients_served_label: "Patients served",
  call_to_know: "Call to know",
  serial_note: "Please arrive on time to confirm your serial. Call the helpline for urgent needs.",
  location_view: "View location",
  specialist: "Specialist",

  booking_title: "Book Appointment",
  step_datetime: "Date & Time",
  step_patient: "Patient Info",
  step_confirm: "Confirm",
  select_chamber: "Select chamber",
  select_date: "Select date",
  select_time: "Select time",
  next_step: "Next Step",
  prev_step: "Back",
  patient_info_title: "Enter patient details",
  patient_name: "Patient name",
  patient_name_placeholder: "Enter full name",
  mobile_number: "Mobile number",
  age: "Age",
  age_placeholder: "Years",
  problem_label: "Problem or symptoms (brief)",
  problem_placeholder: "What do you want to consult about",
  confirm_booking: "Confirm Appointment",
  booking_pending: "Booking...",
  booking_success_title: "Appointment Confirmed",
  booking_success_sub: "Your serial has been booked successfully. We'll confirm over the phone.",
  doctor_label: "Doctor",
  datetime_label: "Date & Time",
  serial_label: "Serial No.",
  back_home: "Back to Home",

  spec_page_title_prefix: "Best",
  spec_page_title_suffix: "Doctors in Khulna",
  spec_list_prefix: "List of",
  spec_list_suffix: "doctors in Khulna",
  spec_by_area: "by area",
  spec_faq_suffix: "FAQ",
  area_page_suffix: "Doctors & Chambers",
  search_by_specialty: "Browse by specialty",
  area_doctors_suffix: " doctors",
  combo_title_mid: "in",
  combo_doctor: "Doctors",
  no_spec_doctors: "Doctors in this specialty are coming soon. Call our helpline for help:",
  no_area_doctors: "Doctors in this area are coming soon. Call our helpline for help:",
  no_combo_doctors_1: "currently has no listed",
  no_combo_doctors_2: "doctors.",
  see_all_spec_prefix: "See all",
  see_all_spec_suffix: "doctors in Khulna →",
  other_areas_prefix: "In other areas:",
  other_specialties: "Other Specialties",

  hospitals_title: "Nearest Hospitals & Clinics",
  hospitals_sub: "Find well-known hospitals and clinics near you by area, with departments and doctor counts in one place.",
  departments_count_suffix: " departments",
  doctors_count_suffix: "+ doctors",
  view_details: "View details",
  area_label: "Area",
  departments: "Departments",
  location: "Location",
  gallery: "Gallery",
  view_map: "View map",
  hospital_doctors: "Doctors at this hospital",
  doctors_info_soon: "Doctor information coming soon.",
  khulna: "Khulna",
  filter_by_name: "Filter by name",
  filter_by_department: "Filter by department",

  blog_title: "Health Tips & Blog",
  blog_sub: "Read simple advice and expert articles on staying healthy.",
  all: "All",
  no_articles: "Articles coming soon.",
  article_disclaimer: "This article is for general health awareness only. It is not medical advice, a diagnosis, or a substitute for treatment. If symptoms appear, please consult a registered physician. In an emergency, call 999 or go to the nearest hospital without delay.",
  article_cta: "Looking for a good doctor?",
  find_doctor: "Find Doctors",

  fordoc_hero_title: "Reach thousands of patients with your profile",
  fordoc_call_cta: "Call",
  plans_title: "Promotion Plans",
  plans_sub: "Pick the plan that fits your needs. Contact us to join any plan.",
  plan_popular: "Popular",
  plan_cta: "Choose This Plan",

  contact_title: "Contact Us",
  contact_sub: "We're here for you. Reach us through any of the channels below.",
  contact_patient_title: "Support for Patients",
  contact_patient_text: "Contact our helpline to find doctors, book appointments or for any assistance.",
  contact_patient_cta: "Call the helpline",
  contact_doctor_title: "Profile Listing for Doctors",
  contact_doctor_text: "Talk to us about getting verified, featured or promoted.",
  contact_doctor_cta: "Contact for promotion",
  contact_form_title: "Send us a message",
  your_name: "Your name",
  your_email: "Your email (optional)",
  your_message: "Write your message",
  send: "Send",
  sending: "Sending...",
  direct_contact: "Direct Contact",
  whatsapp_message: "Message us on WhatsApp",
  our_address: "Our address",

  hub_areas_title_tpl: "Doctors by Area in {d}",
  hub_areas_desc: "Pick the thana or upazila nearest to you. Chambers, schedules and visit fees are listed separately for each area.",
  hub_specialties_title_tpl: "Specialties in {d}",
  hub_specialties_desc: "If you already know which specialist you need, go straight to that department.",
  hub_hospitals_title_tpl: "Hospitals and Clinics in {d}",
  hub_hospitals_desc: "Browse by hospital to see its doctors, departments and contact details.",
  hub_area_specialties_title_tpl: "Doctors by Specialty in {a}",
  hub_area_specialties_desc: "The specialties that currently have doctors in this area. Go straight to the one you need.",
  hub_specialty_districts_title_tpl: "{s} Specialists by District",
  hub_specialty_districts_desc: "Districts that currently have doctors in this specialty. Pick yours to see only its list.",
  hub_specialty_areas_title_tpl: "{s} Doctors by Area",
  hub_specialty_areas_desc: "Areas that currently have doctors in this specialty. Pick the one nearest to you.",
  coming_soon: "Coming soon",
  hub_popular_searches_title: "Popular Searches",
  hub_popular_searches_desc: "The specialty and area combinations people look for most. Jump straight to the list.",
  hub_recent_doctors_title: "Recently Updated Doctors",
  hub_recent_doctors_desc: "Profiles whose details, chambers or schedules were verified and updated most recently.",
  hub_districts_title: "Doctors by District",
  hub_districts_desc: "Districts across Bangladesh where we have verified doctors. Pick yours.",
  view_all_districts: "View all districts",
  hub_nearby_areas_title_tpl: "Nearby Areas in {d}",
  hub_nearby_areas_desc: "Doctors in the other thanas and upazilas of the same district.",
  hub_related_title: "Related pages",
  hub_all_area_doctors_tpl: "All doctors in {a}",
  hub_all_district_doctors_tpl: "All doctors in {d}",
  view_all_areas: "View all areas",
  view_all_specialties: "View all specialties",
  view_all_hospitals: "View all hospitals",
  org_knows_about: "Specialist doctor directory|Doctor chambers and schedules|Hospitals and clinics|Doctor appointments|Healthcare information in Bangladesh",
  district_intro_fallback_tpl: "The complete list of verified doctors in {d}, in one place. Every profile carries degrees, experience, chamber address, sitting hours and visit fee, so you know where to go and when before you leave home. Filter by specialty, area or hospital to find a doctor near you and book directly.",
  district_faq_title: "Frequently Asked Questions",

  about_suffix: "About",
  about_intro_1: "is a trusted doctor directory for Bangladesh. Our goal is for everyone to easily find the right specialist in their area and book appointments without hassle.",
  our_values: "Our Values",
  value1_title: "Trust",
  value1_text: "Every doctor is verified before being listed.",
  value2_title: "Accessibility",
  value2_text: "Find doctors easily from any area.",
  value3_title: "Patient Care",
  value3_text: "We value patients' time and convenience above all.",
  about_cta: "Find your doctor now",

  about_how_title: "How this directory works",
  about_how_text: "We do not run a hospital or a chamber, and we do not provide medical care. We are a directory: we collect doctors' public practice information in one place so you can find it and get in touch. Appointment requests are passed on to the chamber concerned.",
  about_verify_title: "How we verify information",
  about_verify_intro: "Every profile goes through these steps before it is published:",
  about_verify_1: "Information is collected directly from the doctor or their chamber, or from a hospital's public listing.",
  about_verify_2: "Name, degrees and specialty are cross-checked against what the chamber or hospital states.",
  about_verify_3: "Chamber address, sitting hours and visit fee are confirmed by phone before publishing.",
  about_verify_4: "Once that is done the profile carries a verified badge. Profiles that have not been through this do not carry it.",
  about_verified_badge_note: "The verified badge means we checked that the listed details are accurate. It is not our assessment of any doctor's quality of care.",
  about_editorial_title: "Updates and editorial policy",
  about_editorial_text: "Chamber hours and fees change, so we review listings regularly and correct anything reported to us once we have checked it. Blog articles are general health information, not a diagnosis or a treatment plan for any specific condition.",
  about_disclaimer_title: "Medical disclaimer",
  about_disclaimer_text: "Nothing on this site replaces a doctor's advice. For any health problem, consult a qualified physician in person. In an emergency go to the nearest hospital without delay, or call the national emergency number 999.",
  about_publisher_title: "Publisher and contact",
  about_publisher_text: "This site is operated by:",
  about_correction_title: "Report incorrect information",
  about_correction_text: "If a doctor's details look wrong or out of date, tell us. We will check, correct it, or remove the profile.",
  about_correction_cta: "Report a correction",

  footer_tagline: "Khulna's trusted doctor directory. Find verified doctors by area and specialty, and book appointments easily.",
  footer_popular_specs: "Popular Specialties",
  footer_by_area: "By Area",
  footer_area_doctors_suffix: " doctors",
  footer_quick_links: "Quick Links",
  footer_for_doctors: "For Doctors",
  footer_for_doctors_text: "Contact us to list your profile or get promoted as a doctor.",
  footer_contact_cta: "Contact Us",
  footer_rights: "All rights reserved.",
  terms: "Terms of Service",
  privacy: "Privacy Policy",

  doctors_unit: "doctors",
  posts_unit: "posts",
  not_found_title: "Sorry, page not found",
  not_found_sub: "The page you're looking for may have been moved or its address has changed.",
  error_title: "Something went wrong",
  error_sub: "A server error occurred. Please try again shortly.",
  try_again: "Try Again",
};


export type Dict = typeof bn;

export function getDict(locale: Locale): Dict {
  return locale === "en" ? en : bn;
}
