import "server-only";
import type { SiteSettings } from "./settings";
import { date as fmtDate } from "./i18n";
import { siteUrl } from "./seo-utils";

/**
 * Emails always sign with the ENGLISH site name. It is the one name Google and
 * the inbox both see for this domain, it needs no RFC 2047 encoding in a
 * header, and a consistent Latin sender name is easier for a recipient to
 * recognise than a transliterated one.
 */
const EMAIL_BRAND = "Doctors Find Bangladesh";

// Visitor-facing email templates.
//
// Deliverability rules these follow, because a confirmation that lands in spam
// is worse than no confirmation at all:
//   - No images and no external CSS. Image-heavy mail with a poor text ratio is
//     a classic spam signal, and most clients block remote images by default
//     anyway, so a logo would render as a broken box on first open.
//   - Table layout with inline styles only; <style> blocks get stripped.
//   - A real plain-text alternative is generated by the mailer.
//   - Short subject with no ALL CAPS, no "!!!", no money/urgency words.
//   - A hidden preheader controls the inbox preview line instead of letting the
//     client scrape whatever markup comes first.
//   - Links point only at our own domain and the site's official social pages.

const BRAND = "#0B7F75"; // brand-600
const INK = "#0F172A";
const INK_SOFT = "#334155";
const INK_GHOST = "#8593A0";
const LINE = "#E4E9EE";
const PAGE = "#F4F6F8";
// Second accent, used only for the doctor + chamber panel so it reads as a
// distinct block rather than more body text.
const ACCENT_BG = "#F0FDFA"; // brand-50
const ACCENT_LINE = "#99F6E4"; // brand-200
const ACCENT_TEXT = "#0F766E"; // brand-700

/** Escapes user-supplied text so a name or message can never inject markup. */
export function esc(value: string | null | undefined): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Admins often paste a bare domain; make it a usable absolute URL. */
function absoluteUrl(raw: string): string | null {
  const v = (raw || "").trim();
  if (!v) return null;
  const withScheme = /^https?:\/\//i.test(v) ? v : `https://${v}`;
  try {
    return new URL(withScheme).toString();
  } catch {
    return null;
  }
}

type SocialLink = { label: string; url: string };

/**
 * Only the socials the admin actually filled in. An empty Instagram field means
 * Instagram simply does not appear in the email.
 */
function socialLinks(s: SiteSettings): SocialLink[] {
  const candidates: [string, string][] = [
    ["ফেসবুক", s.facebook],
    ["ইউটিউব", s.youtube],
    ["ইনস্টাগ্রাম", s.instagram],
  ];
  const out: SocialLink[] = [];
  for (const [label, raw] of candidates) {
    const url = absoluteUrl(raw);
    if (url) out.push({ label, url });
  }
  return out;
}

/**
 * Doctor and chamber shown as one tinted panel in the secondary accent, so the
 * "which visit is this about" facts stand apart from the surrounding sentences
 * in both emails. Rows with no value are dropped rather than printed empty.
 */
export function visitPanel(opts: {
  doctorName: string;
  /** Public profile slug — turns the doctor's name into a link when present. */
  doctorSlug?: string | null;
  chamberName?: string | null;
  chamberAddress?: string | null;
  visitDate?: string | null;
  timeSlot?: string | null;
  serial?: string | null;
  fee?: number | null;
}): string {
  const line = (label: string, value: string) =>
    `<tr>
       <td style="padding:3px 0;font-size:12.5px;color:${ACCENT_TEXT};opacity:.85;width:78px;vertical-align:top;">${label}</td>
       <td style="padding:3px 0;font-size:14px;color:${INK};font-weight:600;">${value}</td>
     </tr>`;

  // Bangla is served from the root path, so no locale prefix here.
  const doctorHref = opts.doctorSlug ? siteUrl(`/doctors/${opts.doctorSlug}`) : null;

  const rows = [
    line(
      "ডাক্তার",
      doctorHref
        ? `<a href="${esc(doctorHref)}" style="color:${ACCENT_TEXT};text-decoration:underline;">${esc(opts.doctorName)}</a>`
        : esc(opts.doctorName)
    ),
    opts.chamberName ? line("চেম্বার", esc(opts.chamberName)) : "",
    opts.chamberAddress ? line("ঠিকানা", esc(opts.chamberAddress)) : "",
    opts.visitDate ? line("তারিখ", `${esc(opts.visitDate)}${opts.timeSlot ? `, ${esc(opts.timeSlot)}` : ""}`) : "",
    opts.serial ? line("সিরিয়াল", `<span style="font-family:ui-monospace,Menlo,monospace;">${esc(opts.serial)}</span>`) : "",
    opts.fee ? line("ভিজিট ফি", `${esc(String(opts.fee))} টাকা`) : "",
  ].join("");

  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${ACCENT_BG};border:1px solid ${ACCENT_LINE};border-radius:10px;margin:0 0 14px;">
      <tr><td style="padding:12px 14px;">
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%">${rows}</table>
      </td></tr>
    </table>`;
}

/**
 * Branded shell. `preheader` is the line the inbox shows next to the subject;
 * it is hidden inside the message body itself.
 *
 * `contactOverride` replaces the site helpline with a chamber's own serial
 * number, so an appointment email points at the desk that actually took it.
 */
function brandedEmail(opts: {
  brandName: string;
  preheader: string;
  heading: string;
  bodyHtml: string;
  settings: SiteSettings;
  contactOverride?: { label: string; display: string; dial: string } | null;
  /** Sentence introducing the website link, worded per template. */
  siteLinkLabel: string;
  /**
   * Closing line under the divider. Defaults to the automatic-message notice the
   * receipts carry, because they are sent from a noreply address. A template
   * whose replies actually reach a person overrides it and says so.
   */
  footerNote?: string;
  /**
   * Body width in pixels. 620 suits the short receipts; templates carrying a
   * long URL or several paragraphs pass more so lines break less often.
   */
  maxWidth?: number;
}): string {
  const { brandName, preheader, heading, bodyHtml, settings, contactOverride, siteLinkLabel } = opts;
  const maxWidth = opts.maxWidth ?? 620;
  const footerNote = opts.footerNote ?? "এটি একটি স্বয়ংক্রিয় বার্তা, এই ইমেইলের উত্তর দেওয়ার প্রয়োজন নেই।";

  const helplineDisplay = contactOverride
    ? contactOverride.display
    : settings.helpline_bn?.trim() || settings.helpline?.trim() || "";
  const helplineDial = contactOverride ? contactOverride.dial : settings.helpline?.trim() || "";
  const helplineLabel = contactOverride ? contactOverride.label : "যেকোনো প্রয়োজনে হেল্পলাইন:";
  const socials = socialLinks(settings);

  const helplineBlock = helplineDisplay
    ? `<tr><td class="em-pad" style="padding:0 26px 18px 26px;">
         <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${PAGE};border-radius:10px;">
           <tr><td style="padding:14px 16px;font-size:14px;color:${INK_SOFT};">
             ${esc(helplineLabel)}
             ${helplineDial
               ? `<a href="tel:${esc(helplineDial)}" style="color:${BRAND};font-weight:700;text-decoration:none;">${esc(helplineDisplay)}</a>`
               : `<span style="color:${BRAND};font-weight:700;">${esc(helplineDisplay)}</span>`}
           </td></tr>
         </table>
       </td></tr>`
    : "";

  const socialBlock = socials.length
    ? `<tr><td class="em-pad" style="padding:0 26px 22px 26px;font-size:13.5px;color:${INK_GHOST};">
         আমাদের সাথে থাকুন:
         ${socials
           .map(
             (l) =>
               `<a href="${esc(l.url)}" style="color:${BRAND};text-decoration:none;font-weight:600;">${esc(l.label)}</a>`
           )
           .join(`<span style="color:${LINE};"> | </span>`)}
       </td></tr>`
    : "";

  // One link to our own site, with descriptive Bangla wording and the brand as
  // the anchor text. Deliberately not a big "CLICK HERE" button: a plain,
  // relevant link on the sending domain is what keeps a transactional mail out
  // of the spam folder.
  const siteBlock = `<tr><td class="em-pad" style="padding:0 26px 22px 26px;font-size:13.5px;color:${INK_GHOST};">
         ${esc(siteLinkLabel)}
         <a href="${esc(siteUrl("/"))}" style="color:${BRAND};text-decoration:none;font-weight:600;">${esc(brandName)}</a>
       </td></tr>`;

  // Responsiveness comes from the inline styles first: the outer table is
  // width="100%" and the card is capped with max-width, so it already shrinks to
  // any viewport without a single media query. The <style> block below is pure
  // enhancement — it only trims the generous desktop side padding on narrow
  // screens. Clients that strip <style> (some webmail does) lose nothing but a
  // few pixels of margin, which is exactly why the padding is not ONLY there.
  const responsiveCss = `
    @media only screen and (max-width:600px) {
      .em-shell { padding:12px 8px !important; }
      .em-card { border-radius:12px !important; }
      .em-pad { padding-left:16px !important; padding-right:16px !important; }
      .em-h1 { font-size:16px !important; }
      .em-body { font-size:14px !important; line-height:1.75 !important; }
    }`;

  return `<!doctype html>
<html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(heading)}</title><style>${responsiveCss}</style></head>
<body style="margin:0;padding:0;background:${PAGE};">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${esc(preheader)}</div>
  <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${PAGE};">
    <tr><td align="center" class="em-shell" style="padding:24px 12px;">
      <table role="presentation" cellpadding="0" cellspacing="0" width="100%" class="em-card" style="max-width:${maxWidth}px;background:#FFFFFF;border:1px solid ${LINE};border-radius:14px;overflow:hidden;font-family:system-ui,-apple-system,'Segoe UI',Roboto,Arial,sans-serif;">
        <tr><td class="em-pad" style="background:${BRAND};padding:16px 26px;">
          <span style="color:#FFFFFF;font-size:16px;font-weight:700;">${esc(brandName)}</span>
        </td></tr>
        <tr><td class="em-pad" style="padding:24px 26px 6px 26px;">
          <h1 class="em-h1" style="margin:0;font-size:17px;line-height:1.5;font-weight:700;color:${INK};">${esc(heading)}</h1>
        </td></tr>
        <tr><td class="em-pad em-body" style="padding:6px 26px 18px 26px;font-size:14.5px;line-height:1.8;color:${INK_SOFT};">
          ${bodyHtml}
        </td></tr>
        ${helplineBlock}
        ${siteBlock}
        ${socialBlock}
        <tr><td class="em-pad" style="border-top:1px solid ${LINE};padding:14px 26px;font-size:12px;line-height:1.6;color:${INK_GHOST};">
          ${esc(footerNote)}<br>${esc(brandName)}
        </td></tr>
      </table>
    </td></tr>
  </table>
</body></html>`;
}

/**
 * The single email a contact-form submission produces. It goes to the visitor
 * when they supplied an address, with the team on BCC; when they did not, only
 * the BCC copies go out. Because the same message serves both audiences it
 * restates what was submitted, which doubles as the visitor's own receipt.
 * Bangla only, by request.
 */
export function contactConfirmationEmail(opts: {
  name: string;
  phone: string;
  email?: string | null;
  message?: string | null;
  settings: SiteSettings;
}): { subject: string; html: string } {
  const { name, phone, email, message, settings } = opts;
  const brandName = brandOf(settings);

  const row = (label: string, value: string) =>
    `<tr>
       <td style="padding:4px 0;font-size:13px;color:${INK_GHOST};width:74px;vertical-align:top;">${label}</td>
       <td style="padding:4px 0;font-size:14px;color:${INK};">${value}</td>
     </tr>`;

  return {
    // Names the brand and states the outcome, so it is recognisable in a list
    // and reads as a reply to something the visitor just did.
    subject: `${brandName}: আপনার বার্তা পেয়েছি`,
    html: brandedEmail({
      brandName,
      preheader: "আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
      siteLinkLabel: "আমাদের সেবা সম্পর্কে আরও জানতে দেখুন:",
      heading: `ধন্যবাদ ${name.trim()}`,
      bodyHtml: `
        <p style="margin:0 0 14px;">আপনার বার্তা আমরা পেয়েছি। আমাদের টিম দেখে শীঘ্রই আপনার সাথে যোগাযোগ করবে।</p>
        <p style="margin:0 0 6px;font-size:13px;color:${INK_GHOST};">আপনার দেওয়া তথ্য</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:0 0 14px;">
          ${row("নাম", esc(name))}
          ${row("ফোন", `<a href="tel:${esc(phone)}" style="color:${BRAND};text-decoration:none;">${esc(phone)}</a>`)}
          ${email ? row("ইমেইল", `<a href="mailto:${esc(email)}" style="color:${BRAND};text-decoration:none;">${esc(email)}</a>`) : ""}
          ${row("বার্তা", esc(message || "-").replace(/\n/g, "<br>"))}
        </table>
        <p style="margin:0;">জরুরি প্রয়োজন হলে নিচের নম্বরে সরাসরি কল করতে পারেন।</p>`,
      settings,
    }),
  };
}

/**
 * The invitation a doctor (or their chamber staff) gets after they pay to be
 * listed: one private link to the intake form.
 *
 * Three things it has to get right. Deliverability first: a stranger receiving
 * a link is exactly the shape of mail that spam filters distrust, so it stays on
 * the same table-and-inline-styles shell as the receipts, carries a plain-text
 * part, and links only to our own domain. Then the single-use rule, which has to
 * be unmistakable, because a client who fills half a form and comes back to a
 * dead link will give up rather than call. And finally it is a real
 * conversation, not a receipt: replies reach the contact inbox (sendIntakeLink
 * sets Reply-To), so the footer invites them instead of warning them off.
 */
export function doctorFormInviteEmail(opts: {
  clientName: string;
  formUrl: string;
  settings: SiteSettings;
}): { subject: string; html: string } {
  const { clientName, formUrl, settings } = opts;
  const brandName = brandOf(settings);
  const name = clientName.trim();

  return {
    // States what it is and who it is from. No urgency words, no capitals, no
    // exclamation marks — all three are spam signals on a first-contact mail.
    subject: `${brandName}: ডাক্তারের প্রোফাইল তথ্যের ফর্ম`,
    html: brandedEmail({
      brandName,
      // Wider than the receipts: this one carries a full-length URL plus several
      // paragraphs, and at 620px the link wrapped onto three lines.
      maxWidth: 700,
      preheader: "লিংকে ক্লিক করে ফর্মটি পূরণ করুন। ফর্মটি একবারই জমা দেওয়া যাবে।",
      siteLinkLabel: "আমাদের ওয়েবসাইট:",
      footerNote:
        "কিছু জানার থাকলে এই ইমেইলের উত্তর দিতে পারেন, অথবা উপরের হেল্পলাইন নম্বরে কল করুন।",
      heading: name ? `${name}, আপনার ফর্মের লিংক` : "আপনার ফর্মের লিংক",
      bodyHtml: `
        <p style="margin:0 0 14px;">
          আমাদের ওয়েবসাইটে ডাক্তারের প্রোফাইল যুক্ত করার জন্য কিছু তথ্য দরকার।
          নিচের লিংকে ক্লিক করে ফর্মটি পূরণ করে দিন, আমরা সেই তথ্য দিয়েই প্রোফাইলটি তৈরি করব।
        </p>
        <p style="margin:0 0 14px;">
          ফর্মে ডাক্তারের নাম, ডিগ্রি ও পদবি, বিশেষজ্ঞ বিভাগ, হাসপাতাল, চেম্বারের ঠিকানা,
          সময়সূচি, ভিজিট ফি আর সিরিয়াল নম্বর লাগবে। ডাক্তারের একটি ছবিও দিতে হবে,
          তাই ছবিটি হাতের কাছে রেখে শুরু করলে সুবিধা হবে।
        </p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${ACCENT_BG};border:1px solid ${ACCENT_LINE};border-radius:10px;margin:0 0 14px;">
          <tr><td style="padding:14px 16px;">
            <div style="font-size:12.5px;color:${ACCENT_TEXT};opacity:.85;margin:0 0 6px;">আপনার ফর্মের লিংক</div>
            <a href="${esc(formUrl)}" style="font-size:14px;font-weight:700;color:${BRAND};text-decoration:underline;word-break:break-all;">${esc(formUrl)}</a>
          </td></tr>
        </table>
        <p style="margin:0 0 14px;">
          একটি বিষয় খেয়াল রাখবেন। এই লিংক দিয়ে <b>শুধু একবারই</b> ফর্ম জমা দেওয়া যাবে,
          একবার জমা দেওয়ার পর লিংকটি আর কাজ করবে না। তাই তথ্যগুলো ঠিক আছে কিনা দেখে নিয়ে
          তারপর জমা দিন। পরে কিছু বদলাতে হলে বা নতুন করে ফর্ম লাগলে আমাদের সাথে যোগাযোগ
          করলেই আমরা নতুন একটি লিংক পাঠিয়ে দেব।
        </p>
        <p style="margin:0;">
          ফর্ম পূরণ করতে কোনো অসুবিধা হলে এই ইমেইলের উত্তর দিন অথবা নিচের নম্বরে কল করুন,
          আমরা সাহায্য করব।
        </p>`,
      settings,
    }),
  };
}

/**
 * Internal copy, sent to the contact address the moment a form lands, so nobody
 * has to keep the dashboard open to know a lead arrived. Bangla like the rest,
 * but the phone, email and fee stay in Latin digits because staff copy them.
 */
export function doctorFormSubmittedEmail(opts: {
  clientName: string;
  clientPhone: string;
  clientEmail?: string | null;
  doctorName: string;
  hospital?: string | null;
  specialty?: string | null;
  chamberName?: string | null;
  district?: string | null;
  area?: string | null;
  fee?: number | null;
  serialPhone?: string | null;
  settings: SiteSettings;
}): { subject: string; html: string } {
  const { settings } = opts;
  const brandName = brandOf(settings);

  const row = (label: string, value: string) =>
    `<tr>
       <td style="padding:4px 0;font-size:13px;color:${INK_GHOST};width:96px;vertical-align:top;">${label}</td>
       <td style="padding:4px 0;font-size:14px;color:${INK};">${value}</td>
     </tr>`;

  const dashboardUrl = siteUrl("/admin/doctor-forms");

  return {
    subject: `নতুন ডাক্তার ফর্ম জমা পড়েছে: ${opts.doctorName.trim()}`,
    html: brandedEmail({
      brandName,
      preheader: `${opts.clientName.trim()} ফর্মটি জমা দিয়েছেন, ফোন ${opts.clientPhone}`,
      siteLinkLabel: "ওয়েবসাইট:",
      heading: "নতুন ডাক্তার ফর্ম জমা পড়েছে",
      bodyHtml: `
        <p style="margin:0 0 14px;">পাঠানো লিংক থেকে একজন ফর্মটি পূরণ করে জমা দিয়েছেন। সম্পূর্ণ তথ্য ও ছবি ড্যাশবোর্ডে দেখা যাবে।</p>
        <p style="margin:0 0 6px;font-size:13px;color:${INK_GHOST};">যিনি জমা দিয়েছেন</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:0 0 14px;">
          ${row("নাম", esc(opts.clientName))}
          ${row("ফোন", `<a href="tel:${esc(opts.clientPhone)}" style="color:${BRAND};text-decoration:none;font-weight:700;">${esc(opts.clientPhone)}</a>`)}
          ${opts.clientEmail ? row("ইমেইল", `<a href="mailto:${esc(opts.clientEmail)}" style="color:${BRAND};text-decoration:none;">${esc(opts.clientEmail)}</a>`) : ""}
        </table>
        <p style="margin:0 0 6px;font-size:13px;color:${INK_GHOST};">ডাক্তারের তথ্য</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:0 0 14px;">
          ${row("ডাক্তার", esc(opts.doctorName))}
          ${opts.specialty ? row("বিভাগ", esc(opts.specialty)) : ""}
          ${opts.hospital ? row("হাসপাতাল", esc(opts.hospital)) : ""}
          ${opts.chamberName ? row("চেম্বার", esc(opts.chamberName)) : ""}
          ${opts.district || opts.area ? row("এলাকা", esc([opts.area, opts.district].filter(Boolean).join(", "))) : ""}
          ${opts.fee ? row("ভিজিট ফি", `${esc(String(opts.fee))} টাকা`) : ""}
          ${opts.serialPhone ? row("সিরিয়াল নম্বর", esc(opts.serialPhone)) : ""}
        </table>
        <p style="margin:0;">
          ড্যাশবোর্ডে দেখুন:
          <a href="${esc(dashboardUrl)}" style="color:${BRAND};font-weight:700;text-decoration:underline;">ডাক্তার ফর্ম</a>
        </p>`,
      settings,
    }),
  };
}

/** Shared shape for both appointment emails. */
export type AppointmentMailInput = {
  patientName: string;
  phone: string;
  email?: string | null;
  age?: string | null;
  problem?: string | null;
  visitDate: string;
  timeSlot: string;
  serial: string;
  doctorName: string;
  doctorSlug?: string | null;
  chamberName?: string | null;
  chamberAddress?: string | null;
  chamberPhone?: string | null;
  fee?: number | null;
  settings: SiteSettings;
};

export function brandOf(settings: SiteSettings): string {
  // English only, and NOT brand_name — that field holds header/footer copy and
  // is currently a full tagline. See EMAIL_BRAND above.
  return settings.site_name?.en?.trim() || EMAIL_BRAND;
}

/**
 * The booking stores an ISO date ("2026-08-10"); nobody wants to read that in
 * an email. Emails are Bangla-only, so this always formats in Bangla.
 */
function readableDate(iso: string): string {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(iso)) return iso;
  return fmtDate(iso, "bn");
}

/**
 * Goes to the patient, only when they gave an address. The promise here is
 * deliberately modest: the booking is a REQUEST, and a person will ring to
 * confirm it. The contact number shown is the chamber's own serial line rather
 * than the site helpline.
 */
export function appointmentPatientEmail(a: AppointmentMailInput): { subject: string; html: string } {
  const brandName = brandOf(a.settings);
  const chamberDial = (a.chamberPhone || "").trim();

  return {
    subject: `${brandName}: আপনার সিরিয়ালের অনুরোধ পেয়েছি (${a.serial})`,
    html: brandedEmail({
      brandName,
      preheader: "আমরা শীঘ্রই ফোন করে আপনার সময় নিশ্চিত করব।",
      siteLinkLabel: "আরও ডাক্তার ও চেম্বারের তথ্য দেখুন:",
      heading: `ধন্যবাদ ${a.patientName.trim()}`,
      bodyHtml: `
        <p style="margin:0 0 14px;">আপনার সিরিয়ালের অনুরোধ আমরা পেয়েছি। আমাদের একজন প্রতিনিধি শীঘ্রই আপনাকে ফোন করে সময়টি নিশ্চিত করবেন।</p>
        ${visitPanel({
          doctorName: a.doctorName,
          doctorSlug: a.doctorSlug,
          chamberName: a.chamberName,
          chamberAddress: a.chamberAddress,
          visitDate: readableDate(a.visitDate),
          timeSlot: a.timeSlot,
          serial: a.serial,
          fee: a.fee,
        })}
        <p style="margin:0;">সময় পরিবর্তন করতে চাইলে বা কোনো তথ্য জানার প্রয়োজন হলে নিচের নম্বরে যোগাযোগ করুন।</p>`,
      settings: a.settings,
      // The chamber's serial line is the number that can actually help with
      // this booking; the site helpline cannot.
      contactOverride: chamberDial
        ? { label: "সিরিয়াল নম্বর (ফোন):", display: chamberDial, dial: chamberDial }
        : null,
    }),
  };
}

/**
 * Goes to the chamber owner, with any BCC addresses copied in. This is the
 * working copy: everything needed to ring the patient back and confirm.
 */
export function appointmentOwnerEmail(a: AppointmentMailInput): { subject: string; html: string } {
  const brandName = brandOf(a.settings);

  const row = (label: string, value: string) =>
    `<tr>
       <td style="padding:4px 0;font-size:13px;color:${INK_GHOST};width:78px;vertical-align:top;">${label}</td>
       <td style="padding:4px 0;font-size:14px;color:${INK};">${value}</td>
     </tr>`;

  return {
    subject: `নতুন সিরিয়াল: ${a.patientName.trim()} (${a.phone}) — ${a.doctorName}`.replace(/—/g, "|"),
    html: brandedEmail({
      brandName,
      preheader: `${a.patientName.trim()} সিরিয়ালের অনুরোধ করেছেন, ফোন ${a.phone}`,
      siteLinkLabel: "ডাক্তারের সম্পূর্ণ প্রোফাইল ও সময়সূচি দেখুন:",
      heading: "নতুন সিরিয়ালের অনুরোধ",
      bodyHtml: `
        <p style="margin:0 0 14px;">ওয়েবসাইট থেকে নতুন একটি সিরিয়ালের অনুরোধ এসেছে। নিচের নম্বরে ফোন করে রোগীর সময়টি নিশ্চিত করুন।</p>
        ${visitPanel({
          doctorName: a.doctorName,
          doctorSlug: a.doctorSlug,
          chamberName: a.chamberName,
          chamberAddress: a.chamberAddress,
          visitDate: readableDate(a.visitDate),
          timeSlot: a.timeSlot,
          serial: a.serial,
          fee: a.fee,
        })}
        <p style="margin:0 0 6px;font-size:13px;color:${INK_GHOST};">রোগীর তথ্য</p>
        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:0 0 14px;">
          ${row("নাম", esc(a.patientName))}
          ${row("ফোন", `<a href="tel:${esc(a.phone)}" style="color:${BRAND};text-decoration:none;font-weight:700;">${esc(a.phone)}</a>`)}
          ${a.email ? row("ইমেইল", `<a href="mailto:${esc(a.email)}" style="color:${BRAND};text-decoration:none;">${esc(a.email)}</a>`) : ""}
          ${a.age ? row("বয়স", esc(a.age)) : ""}
          ${a.problem ? row("সমস্যা", esc(a.problem).replace(/\n/g, "<br>")) : ""}
        </table>
        <p style="margin:0;">${a.email ? "রোগীর ইমেইলে কনফার্মেশন পাঠানো হয়েছে।" : "রোগী ইমেইল ঠিকানা দেননি, তাই তাঁকে কোনো কনফার্মেশন পাঠানো হয়নি।"}</p>`,
      settings: a.settings,
      // Point the desk at the patient, not at a helpline.
      contactOverride: { label: "রোগীর নম্বর:", display: a.phone, dial: a.phone },
    }),
  };
}
