// Curated Lucide icons for doctor / medical / clinic use. Each entry lists
// search tags (English + Bangla + specialty jargon) so admins can type
// "kidney", "কার্ডিও", "xray", "billing", etc. and land on the right glyph
// even when the Lucide name doesn't match. Names are PascalCase — the key
// format lucide-react's `icons` map uses.
export type MedicalIcon = { name: string; tags: string[] };

export const MEDICAL_ICONS: MedicalIcon[] = [
  // ── Vitals / cardiology ────────────────────────────────────────────────
  { name: "Activity", tags: ["heartbeat", "pulse", "ecg", "ekg", "vitals", "monitor", "cardio"] },
  { name: "Heart", tags: ["heart", "cardio", "cardiology", "হার্ট", "কার্ডিও"] },
  { name: "HeartPulse", tags: ["heart", "cardiology", "pulse", "cardio", "হার্ট"] },
  { name: "HeartHandshake", tags: ["care", "support", "compassion"] },
  { name: "HeartCrack", tags: ["heart attack", "cardiac", "cardiology"] },
  { name: "HeartOff", tags: ["cardiac arrest", "no heart"] },
  { name: "Gauge", tags: ["pressure", "blood pressure", "bp", "meter", "monitor"] },

  // ── Neuro / mental health ──────────────────────────────────────────────
  { name: "Brain", tags: ["brain", "neuro", "neurology", "mind", "psychiatry", "ব্রেইন", "নিউরো", "মানসিক"] },
  { name: "BrainCircuit", tags: ["brain", "neuro", "cognitive", "psychology"] },
  { name: "BrainCog", tags: ["brain", "psychiatry", "psychology", "therapy"] },

  // ── Pediatrics / OB-GYN / family ───────────────────────────────────────
  { name: "Baby", tags: ["baby", "infant", "pediatric", "pediatrics", "newborn", "child", "শিশু", "পেডিয়াট্রিক"] },
  { name: "PersonStanding", tags: ["physiotherapy", "physio", "posture", "rehab", "orthopedic", "ফিজিও"] },
  { name: "Users", tags: ["patients", "family", "group", "রোগীগণ", "পরিবার"] },
  { name: "UsersRound", tags: ["family", "group", "team"] },
  { name: "Contact", tags: ["contact", "family doctor", "patient info"] },
  { name: "ContactRound", tags: ["contact", "profile", "patient card"] },

  // ── Eyes / ENT ─────────────────────────────────────────────────────────
  { name: "Eye", tags: ["eye", "vision", "ophthalmology", "sight", "optical", "চোখ", "অপথালমোলজি"] },
  { name: "EyeOff", tags: ["blind", "vision loss"] },
  { name: "Glasses", tags: ["glasses", "spectacles", "vision", "optical", "চশমা"] },
  { name: "Ear", tags: ["ear", "ent", "hearing", "audiology", "otology", "কান", "ইএনটি"] },
  { name: "EarOff", tags: ["deaf", "hearing loss"] },
  { name: "Mic", tags: ["voice", "speech", "throat", "voice therapy"] },
  { name: "MicOff", tags: ["mute", "voice loss"] },

  // ── Doctor / examination / general ─────────────────────────────────────
  { name: "Stethoscope", tags: ["stethoscope", "doctor", "medical", "general", "physician", "ডাক্তার", "চিকিৎসক", "medicine"] },
  { name: "BriefcaseMedical", tags: ["kit", "first aid", "emergency", "medical bag", "প্রাথমিক"] },
  { name: "Cross", tags: ["cross", "medical", "hospital", "aid"] },
  { name: "Plus", tags: ["plus", "medical", "add", "aid"] },
  { name: "CirclePlus", tags: ["add", "new", "medical", "circle plus"] },
  { name: "GraduationCap", tags: ["degree", "qualification", "specialist", "residency", "মেডিকেল কলেজ"] },
  { name: "IdCard", tags: ["id", "license", "bmdc", "identification"] },
  { name: "BadgeCheck", tags: ["verified", "certified", "approved", "trusted"] },
  { name: "Award", tags: ["award", "certification", "recognition"] },
  { name: "Medal", tags: ["medal", "achievement", "award"] },
  { name: "Trophy", tags: ["trophy", "top rated", "best"] },

  // ── Medication / pharmacy ──────────────────────────────────────────────
  { name: "Pill", tags: ["pill", "medicine", "pharmacy", "drug", "capsule", "medication", "ঔষধ", "ফার্মেসী"] },
  { name: "Tablets", tags: ["tablets", "pills", "medicine", "pharmacy", "medication"] },
  { name: "Syringe", tags: ["syringe", "injection", "vaccine", "immunization", "shot", "টিকা", "ইনজেকশন"] },
  { name: "Thermometer", tags: ["thermometer", "fever", "temperature", "জ্বর", "তাপমাত্রা"] },
  { name: "Package", tags: ["medicine delivery", "pharmacy delivery", "pack"] },
  { name: "Truck", tags: ["delivery", "medicine delivery", "ambulance", "logistics"] },

  // ── Lab / diagnostics / pathology ──────────────────────────────────────
  { name: "TestTube", tags: ["lab", "laboratory", "pathology", "sample", "specimen", "প্যাথলজি", "ল্যাব"] },
  { name: "TestTubes", tags: ["lab", "laboratory", "pathology", "samples", "diagnostics"] },
  { name: "FlaskConical", tags: ["lab", "chemistry", "pathology", "biology"] },
  { name: "Microscope", tags: ["microscope", "pathology", "lab", "research", "diagnostics", "মাইক্রোস্কোপ"] },
  { name: "Dna", tags: ["dna", "genetics", "genome", "molecular", "biology", "ডিএনএ", "জেনেটিক্স"] },
  { name: "Atom", tags: ["atom", "chemistry", "research", "science"] },
  { name: "Scan", tags: ["scan", "xray", "mri", "ct", "imaging", "radiology", "এক্সরে", "রেডিওলজি"] },
  { name: "ScanLine", tags: ["scan", "imaging", "radiology"] },
  { name: "ScanSearch", tags: ["scan", "diagnosis", "diagnostic"] },
  { name: "Waves", tags: ["ultrasound", "sonography", "wave", "usg", "আল্ট্রাসাউন্ড"] },
  { name: "Fingerprint", tags: ["fingerprint", "identity", "biometric"] },
  { name: "QrCode", tags: ["qr", "scan code", "patient qr"] },

  // ── Body systems / specialties ─────────────────────────────────────────
  { name: "Bone", tags: ["bone", "orthopedic", "orthopedics", "skeleton", "fracture", "হাড়", "অর্থোপেডিক"] },
  { name: "Wind", tags: ["breath", "asthma", "lung", "respiratory", "pulmonology", "শ্বাস", "ফুসফুস"] },
  { name: "Droplet", tags: ["blood", "drop", "fluid", "hematology", "iv", "kidney", "urology", "diabetes", "রক্ত", "কিডনি", "ডায়াবেটিস"] },
  { name: "Droplets", tags: ["blood", "fluids", "hematology", "urology", "sweat"] },
  { name: "Smile", tags: ["smile", "dental", "teeth", "dentist", "mouth", "oral", "দাঁত", "ডেন্টাল"] },
  { name: "Sun", tags: ["skin", "dermatology", "vitamin d", "sun", "ত্বক", "চর্ম"] },
  { name: "SunMedium", tags: ["skin", "dermatology", "brightness"] },
  { name: "MoonStar", tags: ["sleep therapy", "night care", "insomnia"] },
  { name: "Moon", tags: ["sleep", "night", "insomnia", "ঘুম"] },
  { name: "Leaf", tags: ["ayurvedic", "herbal", "natural", "wellness", "প্রাকৃতিক"] },
  { name: "Flower", tags: ["wellness", "spa", "aromatherapy", "beauty"] },
  { name: "Flower2", tags: ["wellness", "spa", "beauty"] },
  { name: "PawPrint", tags: ["veterinary", "vet", "pet", "animal"] },
  { name: "Snowflake", tags: ["cold therapy", "cryotherapy", "ice"] },
  { name: "Feather", tags: ["allergy", "gentle care", "light touch"] },
  { name: "Cloud", tags: ["asthma", "breathing", "vapor", "nebulizer"] },

  // ── Nutrition / lifestyle ──────────────────────────────────────────────
  { name: "Salad", tags: ["nutrition", "diet", "dietary", "dietitian", "পুষ্টি", "ডায়েট"] },
  { name: "Apple", tags: ["nutrition", "diet", "food", "healthy"] },
  { name: "Utensils", tags: ["diet", "nutrition", "food", "meal"] },
  { name: "Coffee", tags: ["caffeine", "coffee", "lifestyle"] },
  { name: "Cake", tags: ["sugar", "diabetes", "diet", "sweet"] },
  { name: "CakeSlice", tags: ["dessert", "diabetes", "sugar"] },
  { name: "Dumbbell", tags: ["fitness", "exercise", "physiotherapy", "rehab", "physio", "ব্যায়াম"] },
  { name: "Bike", tags: ["exercise", "rehab", "fitness"] },
  { name: "Bath", tags: ["hygiene", "bath", "spa"] },
  { name: "ShowerHead", tags: ["hygiene", "shower", "clean"] },

  // ── Addiction / stop signals ───────────────────────────────────────────
  { name: "Cigarette", tags: ["smoking", "tobacco", "addiction"] },
  { name: "CigaretteOff", tags: ["no smoking", "quit smoking", "stop"] },
  { name: "Wine", tags: ["alcohol", "addiction"] },
  { name: "WineOff", tags: ["no alcohol", "sober"] },
  { name: "Ban", tags: ["prohibited", "not allowed", "stop", "restricted"] },

  // ── Surgery / injury / emergency ───────────────────────────────────────
  { name: "Scissors", tags: ["surgery", "surgical", "operation", "সার্জারি"] },
  { name: "Slice", tags: ["surgery", "surgical", "cut"] },
  { name: "Bandage", tags: ["bandage", "wound", "injury", "dressing", "aid", "ব্যান্ডেজ"] },
  { name: "Zap", tags: ["shock", "defibrillator", "electric", "energy"] },
  { name: "Siren", tags: ["emergency", "urgent", "critical", "911", "ইমার্জেন্সি"] },
  { name: "Ambulance", tags: ["ambulance", "emergency", "er", "urgent", "অ্যাম্বুলেন্স", "ইমার্জেন্সি"] },
  { name: "LifeBuoy", tags: ["rescue", "help", "support", "sos"] },
  { name: "ShieldAlert", tags: ["risk", "alert", "warning", "biohazard"] },
  { name: "TriangleAlert", tags: ["warning", "caution", "risk"] },
  { name: "ShieldPlus", tags: ["insurance", "protection", "coverage"] },
  { name: "ShieldCheck", tags: ["immunity", "protection", "vaccine", "safety", "সুরক্ষা"] },
  { name: "Shield", tags: ["protection", "safety", "immunity"] },

  // ── Facility / rooms ───────────────────────────────────────────────────
  { name: "Hospital", tags: ["hospital", "clinic", "medical center", "হাসপাতাল"] },
  { name: "Building", tags: ["building", "clinic", "chamber", "চেম্বার"] },
  { name: "Building2", tags: ["building", "hospital", "clinic", "corporate"] },
  { name: "Bed", tags: ["bed", "admission", "inpatient", "ward", "ভর্তি", "ওয়ার্ড"] },
  { name: "BedDouble", tags: ["bed", "ward", "inpatient", "cabin"] },
  { name: "Home", tags: ["home", "home care", "visit", "বাসা"] },
  { name: "House", tags: ["home care", "home visit"] },
  { name: "Accessibility", tags: ["disability", "accessibility", "physio", "প্রতিবন্ধী"] },
  { name: "Sparkles", tags: ["cosmetic", "beauty", "aesthetic", "কসমেটিক"] },
  { name: "Sparkle", tags: ["clean", "hygienic", "sanitized"] },
  { name: "WandSparkles", tags: ["treatment", "therapy", "wellness"] },

  // ── Records / appointments / documents ─────────────────────────────────
  { name: "Calendar", tags: ["schedule", "appointment", "booking", "date", "অ্যাপয়েন্টমেন্ট"] },
  { name: "CalendarCheck", tags: ["appointment", "confirmed", "schedule"] },
  { name: "CalendarClock", tags: ["upcoming", "schedule", "appointment time"] },
  { name: "CalendarDays", tags: ["schedule", "calendar", "days"] },
  { name: "CalendarHeart", tags: ["appointment", "checkup", "wellness"] },
  { name: "CalendarPlus", tags: ["book appointment", "new appointment"] },
  { name: "CalendarX", tags: ["cancel", "cancelled", "unavailable"] },
  { name: "Clock", tags: ["time", "schedule", "hours", "সময়"] },
  { name: "AlarmClock", tags: ["reminder", "alarm", "wake up"] },
  { name: "Timer", tags: ["timer", "duration", "waiting time"] },
  { name: "TimerReset", tags: ["reset time", "reschedule"] },
  { name: "Hourglass", tags: ["waiting", "pending", "process"] },
  { name: "History", tags: ["history", "record", "past visits"] },
  { name: "Clipboard", tags: ["chart", "record", "notes"] },
  { name: "ClipboardList", tags: ["chart", "records", "list", "checklist"] },
  { name: "ClipboardCheck", tags: ["checkup", "screening", "chart"] },
  { name: "ClipboardPlus", tags: ["new record", "add note"] },
  { name: "ClipboardPen", tags: ["prescribe", "write", "chart"] },
  { name: "FileText", tags: ["report", "document", "prescription", "rx", "প্রেসক্রিপশন", "রিপোর্ট"] },
  { name: "FileHeart", tags: ["health record", "medical record", "history"] },
  { name: "FileCheck", tags: ["verified", "report ready", "confirmed"] },
  { name: "FilePlus", tags: ["new report", "add document"] },
  { name: "FileSearch", tags: ["find report", "search records"] },
  { name: "Files", tags: ["files", "reports", "documents"] },
  { name: "Notebook", tags: ["notes", "records", "notebook"] },
  { name: "BookOpen", tags: ["knowledge", "guide", "learn", "articles"] },
  { name: "BookHeart", tags: ["patient guide", "wellness guide"] },
  { name: "Book", tags: ["book", "guide", "reference"] },
  { name: "Bookmark", tags: ["saved", "favorite", "bookmark"] },
  { name: "BookmarkCheck", tags: ["saved", "confirmed favorite"] },
  { name: "ScrollText", tags: ["prescription", "rx", "documentation"] },
  { name: "Newspaper", tags: ["news", "articles", "health news", "blog"] },
  { name: "Printer", tags: ["print", "print report", "print prescription"] },

  // ── Billing / payment ──────────────────────────────────────────────────
  { name: "CreditCard", tags: ["payment", "billing", "card", "পেমেন্ট"] },
  { name: "Wallet", tags: ["wallet", "payment", "billing"] },
  { name: "Receipt", tags: ["bill", "receipt", "invoice", "ইনভয়েস"] },
  { name: "Banknote", tags: ["cash", "fees", "money", "টাকা"] },
  { name: "DollarSign", tags: ["fees", "cost", "pricing"] },
  { name: "Coins", tags: ["fees", "coins", "cost"] },
  { name: "HandCoins", tags: ["payment", "fees", "donation"] },

  // ── Contact / telemedicine ─────────────────────────────────────────────
  { name: "Phone", tags: ["phone", "call", "contact", "ফোন"] },
  { name: "PhoneCall", tags: ["call", "contact", "helpline"] },
  { name: "PhoneIncoming", tags: ["incoming call", "receiving"] },
  { name: "PhoneOutgoing", tags: ["outgoing call", "calling"] },
  { name: "Video", tags: ["video", "telemedicine", "consult", "telehealth", "টেলিমেডিসিন"] },
  { name: "Headphones", tags: ["support", "helpline", "customer care"] },
  { name: "MessageCircle", tags: ["chat", "message", "consult"] },
  { name: "MessageCircleHeart", tags: ["care chat", "consult"] },
  { name: "MessageSquare", tags: ["chat", "consult"] },
  { name: "MessagesSquare", tags: ["chats", "conversations"] },
  { name: "Mail", tags: ["email", "contact"] },
  { name: "Send", tags: ["send", "submit", "share"] },
  { name: "Inbox", tags: ["inbox", "messages", "queue"] },
  { name: "Bell", tags: ["notification", "reminder", "alert"] },
  { name: "BellRing", tags: ["reminder", "alarm", "notification"] },
  { name: "BellOff", tags: ["mute", "silent", "no notification"] },
  { name: "MapPin", tags: ["location", "address", "map", "ঠিকানা"] },
  { name: "Map", tags: ["map", "location", "area"] },
  { name: "Navigation", tags: ["directions", "navigate", "route"] },
  { name: "Compass", tags: ["navigate", "direction", "find"] },
  { name: "Route", tags: ["route", "path", "directions"] },
  { name: "Globe", tags: ["global", "international", "web"] },
  { name: "Languages", tags: ["language", "translate", "bilingual", "ভাষা"] },
  { name: "Share2", tags: ["share", "refer", "referral"] },
  { name: "Link", tags: ["link", "url", "connect"] },
  { name: "ExternalLink", tags: ["external", "open link", "visit"] },
  { name: "Download", tags: ["download", "save", "get report"] },
  { name: "Upload", tags: ["upload", "attach", "submit"] },

  // ── Patient identity ───────────────────────────────────────────────────
  { name: "User", tags: ["patient", "person", "user", "রোগী"] },
  { name: "UserRound", tags: ["patient", "person"] },
  { name: "UserPlus", tags: ["new patient", "add patient", "registration"] },
  { name: "UserCheck", tags: ["verified patient", "approved"] },
  { name: "UserX", tags: ["removed", "blocked", "inactive"] },
  { name: "UserSearch", tags: ["find patient", "search patient"] },
  { name: "UserRoundCheck", tags: ["verified", "confirmed patient"] },
  { name: "HandHeart", tags: ["care", "compassion", "support", "donate"] },
  { name: "Handshake", tags: ["partner", "referral", "collaboration"] },
  { name: "Hand", tags: ["hand", "physiotherapy", "physio"] },

  // ── Analytics / dashboard ──────────────────────────────────────────────
  { name: "ChartLine", tags: ["trend", "chart", "analytics", "health trend"] },
  { name: "ChartBar", tags: ["stats", "chart", "analytics"] },
  { name: "ChartPie", tags: ["breakdown", "chart", "analytics"] },
  { name: "TrendingUp", tags: ["improvement", "trend up", "recovery"] },
  { name: "TrendingDown", tags: ["decline", "trend down", "worsening"] },
  { name: "Target", tags: ["goal", "target", "objective"] },

  // ── Status ─────────────────────────────────────────────────────────────
  { name: "CircleCheck", tags: ["ok", "done", "confirmed", "safe"] },
  { name: "CircleCheckBig", tags: ["confirmed", "ok"] },
  { name: "CheckCheck", tags: ["double check", "verified"] },
  { name: "Check", tags: ["check", "done", "confirmed"] },
  { name: "CircleAlert", tags: ["alert", "warning", "attention"] },
  { name: "CircleX", tags: ["cancelled", "not available", "declined"] },
  { name: "CircleHelp", tags: ["help", "faq", "question"] },
  { name: "Info", tags: ["info", "about", "details"] },
  { name: "Flag", tags: ["flag", "report", "priority"] },
  { name: "Star", tags: ["star", "rating", "top rated"] },
  { name: "StarHalf", tags: ["rating", "half star"] },
  { name: "Pin", tags: ["pinned", "important", "sticky"] },
  { name: "PinOff", tags: ["unpin", "remove"] },

  // ── Security / privacy ─────────────────────────────────────────────────
  { name: "Lock", tags: ["privacy", "secure", "encrypted", "গোপনীয়তা"] },
  { name: "Key", tags: ["access", "credentials", "login"] },
  { name: "KeyRound", tags: ["password", "access"] },
  { name: "Vault", tags: ["secure vault", "records", "storage"] },
];
